#!/usr/bin/env python3
"""Generate Roblox Studio command-bar installers from src/.

File mapping (Rojo-compatible):
  dir/                  -> Folder (or the script type of dir/init*.lua, with children)
  Name.server.lua       -> Script
  Name.client.lua       -> LocalScript
  Name.lua              -> ModuleScript

Outputs installer/02_Shared.lua, 03_Server.lua, 04_Client.lua and ALL_IN_ONE.lua.
Part 1 (installer/01_Map.lua) is hand-written and copied into ALL_IN_ONE.lua as-is.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "installer"

PARTS = [
    ("02_Shared.lua", 2, "SHARED CODE (ReplicatedStorage)", 'game:GetService("ReplicatedStorage")', SRC / "ReplicatedStorage" / "HatchOrDie"),
    ("03_Server.lua", 3, "SERVER CODE (ServerScriptService)", 'game:GetService("ServerScriptService")', SRC / "ServerScriptService" / "HatchOrDie"),
    ("04_Client.lua", 4, "CLIENT CODE (StarterPlayerScripts)", 'game:GetService("StarterPlayer"):WaitForChild("StarterPlayerScripts")', SRC / "StarterPlayer" / "StarterPlayerScripts" / "HatchOrDieClient"),
]

HELPER = """local function make(parent, className, name, source)
\tlocal existing = parent:FindFirstChild(name)
\tif existing then
\t\texisting:Destroy()
\tend
\tlocal inst = Instance.new(className)
\tinst.Name = name
\tif source then
\t\tinst.Source = source
\tend
\tinst.Parent = parent
\treturn inst
end
"""


def long_string(text: str) -> str:
    level = 1
    while f"]{'=' * level}]" in text:
        level += 1
    eq = "=" * level
    return f"[{eq}[\n{text}]{eq}]"


def classify(path: Path):
    """Return (className, name) for a source file."""
    name = path.name
    if name.endswith(".server.lua"):
        return "Script", name[: -len(".server.lua")]
    if name.endswith(".client.lua"):
        return "LocalScript", name[: -len(".client.lua")]
    return "ModuleScript", name[: -len(".lua")]


def init_file(directory: Path):
    for candidate, cls in (("init.server.lua", "Script"), ("init.client.lua", "LocalScript"), ("init.lua", "ModuleScript")):
        f = directory / candidate
        if f.exists():
            return f, cls
    return None, "Folder"


def emit(directory: Path, parent_var: str, lines: list, counter: list):
    init, cls = init_file(directory)
    counter[0] += 1
    var = f"n{counter[0]}"
    source = long_string(init.read_text()) if init else "nil"
    lines.append(f'local {var} = make({parent_var}, "{cls}", "{directory.name}", {source})')
    for child in sorted(directory.iterdir()):
        if child == init:
            continue
        if child.is_dir():
            lines.append("do")
            emit(child, var, lines, counter)
            lines.append("end")
        elif child.suffix == ".lua":
            child_cls, child_name = classify(child)
            lines.append(f'make({var}, "{child_cls}", "{child_name}", {long_string(child.read_text())})')


def build_part(number: int, title: str, parent_expr: str, directory: Path) -> str:
    lines = [
        f"-- HATCH OR DIE - installer PART {number} of 4: {title}",
        "-- Generated by tools/build_installer.py from src/. Do not edit by hand.",
        "-- Paste everything into the Roblox Studio command bar and press Enter.",
        HELPER,
    ]
    emit(directory, parent_expr, lines, [0])
    if number == 3:
        lines.append('game:GetService("Players").CharacterAutoLoads = false')
    next_step = "Now run Part %d." % (number + 1) if number < 4 else "All done! Press Play to test, then File > Publish to Roblox."
    lines.append(f'print("✅ HATCH OR DIE Part {number}/4 done. {next_step}")')
    return "\n".join(lines) + "\n"


def main():
    OUT.mkdir(exist_ok=True)
    generated = []
    for filename, number, title, parent_expr, directory in PARTS:
        text = build_part(number, title, parent_expr, directory)
        (OUT / filename).write_text(text)
        generated.append(text)
        print(f"wrote installer/{filename} ({len(text):,} chars)")

    map_part = (OUT / "01_Map.lua").read_text()
    combined = ["-- HATCH OR DIE - ALL-IN-ONE installer (map + all code). Paste into the Studio command bar."]
    for text in [map_part, *generated]:
        combined.append("do\n" + text + "end")
    (OUT / "ALL_IN_ONE.lua").write_text("\n".join(combined) + "\n")
    print(f"wrote installer/ALL_IN_ONE.lua ({sum(len(t) for t in combined):,} chars)")


if __name__ == "__main__":
    main()
