-- HATCH OR DIE - installer PART 2 of 4: SHARED CODE (ReplicatedStorage)
-- Generated by tools/build_installer.py from src/. Do not edit by hand.
-- Paste everything into the Roblox Studio command bar and press Enter.
local function make(parent, className, name, source)
	local existing = parent:FindFirstChild(name)
	if existing then
		existing:Destroy()
	end
	local inst = Instance.new(className)
	inst.Name = name
	if source then
		inst.Source = source
	end
	inst.Parent = parent
	return inst
end

local n1 = make(game:GetService("ReplicatedStorage"), "Folder", "HatchOrDie", nil)
do
local n2 = make(n1, "Folder", "Config", nil)
make(n2, "ModuleScript", "CreatureData", [=[
local Rarity = require(script.Parent.Rarity)

local CreatureData = {}

-- Stage requirements count XP and nights earned *at the current stage*.
CreatureData.Stages = {
	{ Name = "Baby", Scale = 1.0, StatMult = 1.0, XPToEvolve = 100, NightsToEvolve = 1 },
	{ Name = "Teen", Scale = 1.55, StatMult = 1.9, XPToEvolve = 450, NightsToEvolve = 3 },
	{ Name = "Adult", Scale = 2.2, StatMult = 3.3 },
}

CreatureData.Families = {
	Sprout = {
		Rarity = "Common",
		Names = { "Sproutling", "Thornback", "Elderwood Drake" },
		Body = "Lizard",
		Primary = Color3.fromRGB(110, 190, 80),
		Secondary = Color3.fromRGB(215, 235, 160),
		Accent = Color3.fromRGB(255, 120, 150),
		EyeColor = Color3.fromRGB(30, 30, 30),
		Stats = { Health = 140, Damage = 9, AttackRate = 1.1, Range = 7 },
		Ranged = false,
		Ability = { Name = "Thorn Burst", Kind = "Burst", Radius = 16, DamageMult = 2.5, HealOwner = 25, Cooldown = 12 },
		Description = "Tough and loyal. Heals you with Thorn Burst.",
	},
	Ember = {
		Rarity = "Rare",
		Names = { "Emberling", "Cinderfang", "Blaze Wyrm" },
		Body = "Fox",
		Primary = Color3.fromRGB(255, 115, 45),
		Secondary = Color3.fromRGB(255, 225, 190),
		Accent = Color3.fromRGB(255, 225, 80),
		EyeColor = Color3.fromRGB(40, 20, 10),
		Stats = { Health = 100, Damage = 12, AttackRate = 1.0, Range = 22 },
		Ranged = true,
		Ability = { Name = "Fire Nova", Kind = "Burst", Radius = 20, DamageMult = 2.2, Cooldown = 10 },
		Description = "Spits fireballs from range. Fire Nova scorches crowds.",
	},
	Shade = {
		Rarity = "Epic",
		Names = { "Shadeling", "Duskstalker", "Void Sovereign" },
		Body = "Wolf",
		Primary = Color3.fromRGB(75, 55, 125),
		Secondary = Color3.fromRGB(35, 25, 55),
		Accent = Color3.fromRGB(175, 115, 255),
		EyeColor = Color3.fromRGB(175, 115, 255),
		Stats = { Health = 120, Damage = 15, AttackRate = 1.25, Range = 8 },
		Ranged = false,
		Ability = { Name = "Shadow Pounce", Kind = "Pounce", Radius = 40, DamageMult = 4.5, Cooldown = 9 },
		Description = "A fast hunter. Shadow Pounce deletes a single target.",
	},
}

-- Mutations mostly change looks. StatBonus is deliberately small.
CreatureData.Mutations = {
	{ Id = "Storm", Name = "Storm", Weight = 30, Rarity = "Legendary", StatBonus = 0.10, Color = Color3.fromRGB(120, 205, 255) },
	{ Id = "Inferno", Name = "Inferno", Weight = 28, Rarity = "Legendary", StatBonus = 0.10, Color = Color3.fromRGB(255, 85, 20) },
	{ Id = "Crystal", Name = "Crystal", Weight = 20, Rarity = "Legendary", StatBonus = 0.10, Color = Color3.fromRGB(165, 255, 255) },
	{ Id = "Plague", Name = "Plague", Weight = 14, Rarity = "Legendary", StatBonus = 0.10, Color = Color3.fromRGB(145, 255, 60) },
	{ Id = "Void", Name = "Void", Weight = 6, Rarity = "Mythic", StatBonus = 0.15, Color = Color3.fromRGB(95, 0, 170) },
	{ Id = "Rainbow", Name = "Rainbow", Weight = 1.6, Rarity = "Mythic", StatBonus = 0.15, Color = Color3.fromRGB(255, 255, 255) },
	{ Id = "Celestial", Name = "Celestial", Weight = 0.4, Rarity = "Mythic", StatBonus = 0.20, Color = Color3.fromRGB(255, 240, 190) },
}

CreatureData.MutationById = {}
do
	local total = 0
	for _, m in CreatureData.Mutations do
		total += m.Weight
	end
	for _, m in CreatureData.Mutations do
		m.Chance = m.Weight / total
		CreatureData.MutationById[m.Id] = m
	end
end

-- Auras are cosmetic only.
CreatureData.Auras = {
	Fire = { Name = "Fire Aura", Color = Color3.fromRGB(255, 120, 30), Order = 1 },
	Toxic = { Name = "Toxic Aura", Color = Color3.fromRGB(120, 255, 60), Order = 2 },
	Lightning = { Name = "Lightning Aura", Color = Color3.fromRGB(110, 200, 255), Order = 3 },
	Crystal = { Name = "Crystal Aura", Color = Color3.fromRGB(190, 255, 255), Order = 4 },
	Galaxy = { Name = "Galaxy Aura", Color = Color3.fromRGB(170, 90, 255), Order = 5, Robux = true },
	Golden = { Name = "Golden Aura", Color = Color3.fromRGB(255, 205, 60), Order = 6, VIP = true },
}

function CreatureData.RollMutation(rng: Random): string
	local roll = rng:NextNumber()
	local acc = 0
	for _, m in CreatureData.Mutations do
		acc += m.Chance
		if roll <= acc then
			return m.Id
		end
	end
	return CreatureData.Mutations[1].Id
end

function CreatureData.GetStageName(record): string
	local fam = CreatureData.Families[record.Family]
	return fam and fam.Names[record.Stage] or "???"
end

function CreatureData.GetDisplayName(record): string
	local base = CreatureData.GetStageName(record)
	if record.Mutation then
		return record.Mutation .. " " .. base
	end
	return base
end

function CreatureData.GetRarity(record): string
	local fam = CreatureData.Families[record.Family]
	local rarity = fam and fam.Rarity or "Common"
	local mut = record.Mutation and CreatureData.MutationById[record.Mutation]
	if mut then
		rarity = Rarity.Max(rarity, mut.Rarity)
	end
	return rarity
end

function CreatureData.GetStats(record)
	local fam = CreatureData.Families[record.Family]
	local stage = CreatureData.Stages[record.Stage] or CreatureData.Stages[1]
	local mut = record.Mutation and CreatureData.MutationById[record.Mutation]
	local mult = stage.StatMult * (1 + (mut and mut.StatBonus or 0))
	return {
		MaxHealth = math.floor(fam.Stats.Health * mult),
		Damage = math.floor(fam.Stats.Damage * mult * 10) / 10,
		AttackRate = fam.Stats.AttackRate,
		Range = fam.Stats.Range * (0.85 + 0.15 * record.Stage),
	}
end

function CreatureData.CanEvolve(record): (boolean, string?)
	local stage = CreatureData.Stages[record.Stage]
	if not stage or not stage.XPToEvolve then
		return false, "Already fully evolved"
	end
	if (record.XP or 0) < stage.XPToEvolve then
		return false, ("Needs %d more XP"):format(stage.XPToEvolve - (record.XP or 0))
	end
	if (record.StageNights or 0) < stage.NightsToEvolve then
		return false, ("Must survive %d more night(s)"):format(stage.NightsToEvolve - (record.StageNights or 0))
	end
	return true, nil
end

function CreatureData.DiscoveryKey(record): string
	return ("%s:%d:%s"):format(record.Family, record.Stage, record.Mutation or "Normal")
end

return CreatureData
]=])
make(n2, "ModuleScript", "EggData", [=[
-- Pool weights are relative. Odds are shown to players in the Eggs panel (required for paid random items).
local EggData = {
	ForestEgg = {
		Name = "Forest Egg",
		Rarity = "Common",
		HatchTime = 20,
		Price = 75,
		Order = 1,
		Color = Color3.fromRGB(125, 200, 95),
		SpotColor = Color3.fromRGB(95, 70, 45),
		NeonSpots = false,
		MutationChance = 0.02,
		Pool = {
			{ Family = "Sprout", Weight = 70 },
			{ Family = "Ember", Weight = 25 },
			{ Family = "Shade", Weight = 5 },
		},
	},
	EmberEgg = {
		Name = "Ember Egg",
		Rarity = "Rare",
		HatchTime = 40,
		Price = 350,
		Order = 2,
		Color = Color3.fromRGB(255, 125, 45),
		SpotColor = Color3.fromRGB(255, 225, 90),
		NeonSpots = true,
		MutationChance = 0.06,
		Pool = {
			{ Family = "Ember", Weight = 60 },
			{ Family = "Sprout", Weight = 25 },
			{ Family = "Shade", Weight = 15 },
		},
	},
	VoidEgg = {
		Name = "Void Egg",
		Rarity = "Legendary",
		HatchTime = 75,
		Price = 2000,
		Order = 3,
		Color = Color3.fromRGB(85, 40, 160),
		SpotColor = Color3.fromRGB(90, 255, 255),
		NeonSpots = true,
		MutationChance = 0.18,
		Pool = {
			{ Family = "Shade", Weight = 60 },
			{ Family = "Ember", Weight = 30 },
			{ Family = "Sprout", Weight = 10 },
		},
	},
}

return EggData
]=])
make(n2, "ModuleScript", "EnemyData", [=[
local EnemyData = {}

EnemyData.Types = {
	Crawler = {
		Name = "Crawler",
		Shape = "Crawler",
		Behavior = "Melee",
		Health = 38,
		Damage = 7,
		Speed = 17,
		AttackRange = 4.5,
		AttackCooldown = 1.0,
		Windup = 0,
		Coins = 3,
		XP = 7,
		UnlockNight = 1,
		Weight = 60,
		Color = Color3.fromRGB(55, 75, 40),
		EyeColor = Color3.fromRGB(255, 60, 60),
	},
	Hunter = {
		Name = "Hunter",
		Shape = "Hunter",
		Behavior = "Ranged",
		Health = 34,
		Damage = 9,
		Speed = 13,
		AttackRange = 48,
		PreferredRange = 30,
		AttackCooldown = 2.6,
		Windup = 0.8,
		ProjectileSpeed = 70,
		Coins = 5,
		XP = 10,
		UnlockNight = 3,
		Weight = 25,
		Color = Color3.fromRGB(45, 40, 60),
		EyeColor = Color3.fromRGB(255, 70, 220),
	},
	Brute = {
		Name = "Brute",
		Shape = "Brute",
		Behavior = "Melee",
		Health = 240,
		Damage = 26,
		Speed = 8.5,
		AttackRange = 8,
		SmashRadius = 8,
		AttackCooldown = 2.4,
		Windup = 1.0,
		Coins = 15,
		XP = 28,
		UnlockNight = 5,
		Weight = 15,
		Color = Color3.fromRGB(90, 60, 50),
		EyeColor = Color3.fromRGB(255, 150, 30),
	},
	RotwoodColossus = {
		Name = "Rotwood Colossus",
		Shape = "Colossus",
		Behavior = "Boss",
		IsBoss = true,
		Health = 3200,
		Damage = 30,
		Speed = 9,
		AttackRange = 18,
		AttackCooldown = 4.2,
		Windup = 1.3,
		Coins = 0,
		XP = 0,
		Color = Color3.fromRGB(85, 60, 40),
		EyeColor = Color3.fromRGB(140, 255, 90),
	},
}

EnemyData.Variants = {
	Normal = { HealthMult = 1, DamageMult = 1, SpeedMult = 1, RewardMult = 1, Scale = 1 },
	Elite = {
		HealthMult = 2.3,
		DamageMult = 1.5,
		SpeedMult = 1.12,
		RewardMult = 3,
		Scale = 1.3,
		Prefix = "Elite ",
		Tint = Color3.fromRGB(255, 200, 40),
	},
	Nightmare = {
		HealthMult = 3.2,
		DamageMult = 1.9,
		SpeedMult = 1.2,
		RewardMult = 5,
		Scale = 1.4,
		Prefix = "Nightmare ",
		Tint = Color3.fromRGB(210, 0, 45),
	},
}

-- One formula drives every night, so night 1 and night 100 use the same map and code.
function EnemyData.GetNightPlan(night: number, playerCount: number, rng: Random?)
	local n = math.max(1, night)
	local players = math.max(1, playerCount)
	local random = rng or Random.new()

	local plan = {
		Night = n,
		HealthMult = 1 + 0.16 * (n - 1),
		DamageMult = 1 + 0.09 * (n - 1),
		RewardMult = 1,
		TotalEnemies = math.floor((6 + n * 2.5) * (1 + 0.45 * (players - 1))),
		MaxAlive = math.min(10 + n * 2 + (players - 1) * 4, 40),
		EliteChance = if n >= 6 then math.min(0.04 * (n - 5), 0.4) else 0,
		NightmareChance = if n >= 50 then math.min(0.1 + 0.01 * (n - 50), 0.5) else 0,
		Boss = (n % 10 == 0) or n == 25,
		MiniBoss = n == 5,
		Modifier = "Night",
		Types = {},
	}

	if n >= 100 then
		plan.Modifier = "Apocalypse"
		plan.RewardMult = 2
	elseif n >= 50 then
		plan.Modifier = "Nightmare"
		plan.RewardMult = 1.5
	elseif n >= 4 and not plan.Boss and random:NextNumber() < 0.2 then
		plan.Modifier = "BloodMoon"
		plan.RewardMult = 1.5
		plan.TotalEnemies = math.floor(plan.TotalEnemies * 1.3)
		plan.EliteChance = math.max(plan.EliteChance, 0.1)
	end

	for id, data in EnemyData.Types do
		if not data.IsBoss and n >= data.UnlockNight then
			table.insert(plan.Types, { Id = id, Weight = data.Weight })
		end
	end
	table.sort(plan.Types, function(a, b)
		return a.Id < b.Id
	end)

	return plan
end

function EnemyData.PickType(plan, rng: Random): string
	local total = 0
	for _, t in plan.Types do
		total += t.Weight
	end
	local roll = rng:NextNumber() * total
	for _, t in plan.Types do
		roll -= t.Weight
		if roll <= 0 then
			return t.Id
		end
	end
	return plan.Types[1].Id
end

function EnemyData.PickVariant(plan, rng: Random): string
	local roll = rng:NextNumber()
	if roll < plan.NightmareChance then
		return "Nightmare"
	elseif roll < plan.NightmareChance + plan.EliteChance then
		return "Elite"
	end
	return "Normal"
end

return EnemyData
]=])
make(n2, "ModuleScript", "GameConfig", [=[
-- Global tuning knobs. Change numbers here, not in services.
local GameConfig = {
	Version = "0.1.0",

	-- Day / night timing (seconds)
	FirstDayLength = 40,
	DayLength = 50,
	NightLength = 85,
	BossNightLength = 150,
	DayRespawnDelay = 4,
	WipeResetDelay = 7,

	-- Eggs
	StarterEgg = "ForestEgg",
	StarterHatchTime = 10,
	MaxEggs = 30,

	-- Creatures
	BaseCreatureSlots = 15,
	ExtraSlotsBonus = 25,
	CreatureMoveSpeed = 26,
	CreatureLeashDistance = 70,
	CreatureAggroRadius = 40,
	CreatureDefendRadius = 16,
	CreatureKORecoverTime = 25,
	EvolveMutationChance = 0.05,
	FeedXP = 20,
	FeedHealPercent = 0.35,
	FeedCooldown = 0.75,

	-- Player torch
	TorchDamage = 12,
	TorchRange = 10,
	TorchCooldown = 0.45,

	-- World
	GroundY = 0,
	BerryRegrowTime = 40,
	CrystalRegrowTime = 60,
	CrystalCoins = { 8, 15 },

	-- Enemies
	EnemyRetargetInterval = 0.5,
	EnemyAggroRadius = 90,

	-- Saving
	DataStoreName = "HatchOrDie_Players_v1",
	AutosaveInterval = 120,

	-- Optional audio. Paste rbxassetid:// ids to enable music.
	Music = { Day = "", Night = "", Boss = "" },
	Sounds = {
		Hatch = "rbxasset://sounds/electronicpingshort.wav",
		Swing = "rbxasset://sounds/swordslash.wav",
	},

	-- Monetization: create these in Creator Dashboard and paste the ids. 0 = disabled.
	Gamepasses = {
		VIP = 0,
		DoubleHatch = 0,
		AutoHatch = 0,
		ExtraSlots = 0,
	},
	Products = {
		EggPack = 0,
		GalaxyAura = 0,
	},
}

function GameConfig.NightReward(night: number)
	return {
		Coins = 25 + 12 * night,
		CreatureXP = 45 + 10 * night,
		Berries = 2,
	}
end

-- Eggs handed out at dawn for surviving a given night.
function GameConfig.NightEggRewards(night: number): { string }
	local eggs = {}
	if night % 3 == 0 then
		table.insert(eggs, "ForestEgg")
	end
	if night == 5 or night % 7 == 0 then
		table.insert(eggs, "EmberEgg")
	end
	return eggs
end

return GameConfig
]=])
make(n2, "ModuleScript", "Rarity", [=[
local Rarity = {}

Rarity.Order = { "Common", "Uncommon", "Rare", "Epic", "Legendary", "Mythic" }

Rarity.Rank = {}
for i, name in Rarity.Order do
	Rarity.Rank[name] = i
end

Rarity.Colors = {
	Common = Color3.fromRGB(205, 205, 210),
	Uncommon = Color3.fromRGB(95, 225, 115),
	Rare = Color3.fromRGB(70, 155, 255),
	Epic = Color3.fromRGB(185, 95, 255),
	Legendary = Color3.fromRGB(255, 190, 40),
	Mythic = Color3.fromRGB(255, 60, 125),
}

Rarity.ReleaseCoins = {
	Common = 10,
	Uncommon = 20,
	Rare = 40,
	Epic = 80,
	Legendary = 200,
	Mythic = 500,
}

function Rarity.Max(a: string, b: string): string
	return if (Rarity.Rank[a] or 1) >= (Rarity.Rank[b] or 1) then a else b
end

function Rarity.AtLeast(rarity: string, minimum: string): boolean
	return (Rarity.Rank[rarity] or 1) >= (Rarity.Rank[minimum] or 1)
end

return Rarity
]=])
make(n2, "ModuleScript", "ShopData", [=[
local ShopData = {}

ShopData.Categories = { "Eggs", "Boosts", "Cosmetics", "Robux" }

-- Coin shop. Robux items live in ShopData.Robux and are validated server-side via MarketplaceService.
ShopData.Items = {
	{ Id = "ForestEgg", Category = "Eggs", Kind = "Egg", EggId = "ForestEgg", Price = 75, Name = "Forest Egg" },
	{ Id = "EmberEgg", Category = "Eggs", Kind = "Egg", EggId = "EmberEgg", Price = 350, Name = "Ember Egg" },
	{ Id = "VoidEgg", Category = "Eggs", Kind = "Egg", EggId = "VoidEgg", Price = 2000, Name = "Void Egg" },
	{ Id = "Berries5", Category = "Boosts", Kind = "Berries", Amount = 5, Price = 30, Name = "5 Berries", Description = "Feed = XP + heal. Feeding a knocked-out creature revives it." },
	{ Id = "Berries20", Category = "Boosts", Kind = "Berries", Amount = 20, Price = 100, Name = "20 Berries", Description = "Bulk berries for long nights." },
	{ Id = "FireAura", Category = "Cosmetics", Kind = "Aura", AuraId = "Fire", Price = 600, Name = "Fire Aura" },
	{ Id = "ToxicAura", Category = "Cosmetics", Kind = "Aura", AuraId = "Toxic", Price = 900, Name = "Toxic Aura" },
	{ Id = "LightningAura", Category = "Cosmetics", Kind = "Aura", AuraId = "Lightning", Price = 1200, Name = "Lightning Aura" },
	{ Id = "CrystalAura", Category = "Cosmetics", Kind = "Aura", AuraId = "Crystal", Price = 1800, Name = "Crystal Aura" },
}

ShopData.Robux = {
	{ Id = "VIP", Kind = "Gamepass", ConfigKey = "VIP", Robux = 299, Name = "VIP", Description = "VIP tag, Golden Aura, a free Forest Egg every dawn." },
	{ Id = "DoubleHatch", Kind = "Gamepass", ConfigKey = "DoubleHatch", Robux = 99, Name = "2x Hatch Speed", Description = "All eggs hatch twice as fast." },
	{ Id = "AutoHatch", Kind = "Gamepass", ConfigKey = "AutoHatch", Robux = 199, Name = "Auto Hatch", Description = "Your next egg starts incubating automatically." },
	{ Id = "ExtraSlots", Kind = "Gamepass", ConfigKey = "ExtraSlots", Robux = 79, Name = "+25 Creature Slots", Description = "Keep more of your collection." },
	{ Id = "EggPack", Kind = "Product", ConfigKey = "EggPack", Robux = 149, Name = "Ember Egg Pack", Description = "3 Ember Eggs + 200 coins." },
	{ Id = "GalaxyAura", Kind = "Product", ConfigKey = "GalaxyAura", Robux = 129, Name = "Galaxy Aura", Description = "Cosmetic only. Your creature shimmers with stars." },
}

ShopData.ById = {}
for _, item in ShopData.Items do
	ShopData.ById[item.Id] = item
end

return ShopData
]=])
end
do
local n3 = make(n1, "Folder", "Shared", nil)
make(n3, "ModuleScript", "Models", [=[
-- Procedural models built from parts, so the game ships with zero uploaded assets.
-- Every model has an anchored, invisible "Root" PrimaryPart; all other parts are welded to it,
-- so the server only moves Root.CFrame. Attributes: HipHeight (root height above ground), Radius.
local Config = script.Parent.Parent.Config
local CreatureData = require(Config.CreatureData)
local EnemyData = require(Config.EnemyData)
local EggData = require(Config.EggData)

local Models = {}

local function newPart(size: Vector3, color: Color3, material: Enum.Material?, class: string?): BasePart
	local p = Instance.new(class or "Part") :: BasePart
	p.Size = size
	p.Color = color
	p.Material = material or Enum.Material.SmoothPlastic
	p.Anchored = false
	p.CanCollide = false
	p.CanTouch = false
	p.CanQuery = false
	p.Massless = true
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	return p
end

local function ellipsoid(size: Vector3, color: Color3, material: Enum.Material?): BasePart
	local p = newPart(size, color, material)
	local mesh = Instance.new("SpecialMesh")
	mesh.MeshType = Enum.MeshType.Sphere
	mesh.Parent = p
	return p
end

local function wedge(size: Vector3, color: Color3, material: Enum.Material?): BasePart
	return newPart(size, color, material, "WedgePart")
end

local function makeModel(name: string, queryable: boolean)
	local model = Instance.new("Model")
	model.Name = name
	local root = newPart(Vector3.new(1, 1, 1), Color3.new(1, 1, 1))
	root.Name = "Root"
	root.Transparency = 1
	root.Anchored = true
	root.CFrame = CFrame.new()
	root.Parent = model
	model.PrimaryPart = root

	local function add(part: BasePart, offset: CFrame, name: string?): BasePart
		part.CFrame = offset
		part.CanQuery = queryable
		if name then
			part.Name = name
		end
		part.Parent = model
		local weld = Instance.new("WeldConstraint")
		weld.Part0 = root
		weld.Part1 = part
		weld.Parent = part
		return part
	end

	return model, root, add
end

-- Highest point above the root, computed from part CFrames (works before the model is parented).
local function setTop(model: Model)
	local top = 0
	for _, part in model:GetChildren() do
		if part:IsA("BasePart") and part.Name ~= "Root" then
			top = math.max(top, part.CFrame.Position.Y + part.Size.Y / 2)
		end
	end
	model:SetAttribute("Top", top)
end

local function particles(parent: Instance, color: Color3, size: number, rate: number, speed: number?): ParticleEmitter
	local e = Instance.new("ParticleEmitter")
	e.Color = ColorSequence.new(color)
	e.LightEmission = 0.8
	e.Size = NumberSequence.new({ NumberSequenceKeypoint.new(0, size), NumberSequenceKeypoint.new(1, 0) })
	e.Transparency = NumberSequence.new({ NumberSequenceKeypoint.new(0, 0.2), NumberSequenceKeypoint.new(1, 1) })
	e.Lifetime = NumberRange.new(0.8, 1.6)
	e.Rate = rate
	e.Speed = NumberRange.new(speed or 1.5, (speed or 1.5) * 2)
	e.SpreadAngle = Vector2.new(180, 180)
	e.Parent = parent
	return e
end

---------------------------------------------------------------------------------------------------
-- Creatures
---------------------------------------------------------------------------------------------------
function Models.BuildCreature(record): Model
	local fam = CreatureData.Families[record.Family] or CreatureData.Families.Sprout
	local stageIndex = math.clamp(record.Stage or 1, 1, #CreatureData.Stages)
	local s = CreatureData.Stages[stageIndex].Scale
	local mut = record.Mutation and CreatureData.MutationById[record.Mutation]

	local primary, secondary, accent = fam.Primary, fam.Secondary, fam.Accent
	local eyeColor = fam.EyeColor
	local bodyMaterial = Enum.Material.SmoothPlastic
	local accentMaterial = Enum.Material.SmoothPlastic
	if mut then
		primary = primary:Lerp(mut.Color, 0.65)
		secondary = secondary:Lerp(mut.Color, 0.35)
		accent = mut.Color
		accentMaterial = Enum.Material.Neon
		eyeColor = mut.Color
		if mut.Id == "Crystal" then
			bodyMaterial = Enum.Material.Glass
		elseif mut.Id == "Void" then
			primary = Color3.fromRGB(35, 10, 60)
			secondary = Color3.fromRGB(15, 5, 30)
		elseif mut.Id == "Celestial" then
			primary = Color3.fromRGB(255, 250, 235)
			secondary = Color3.fromRGB(255, 225, 150)
		end
	end
	local eyeMaterial = if mut or fam.Body == "Wolf" then Enum.Material.Neon else Enum.Material.SmoothPlastic

	local model, root, add = makeModel(record.Family, false)
	local bodySize = Vector3.new(2.2, 1.7, 2.8) * s
	local legLen = 0.6 * s
	local hip = bodySize.Y / 2 + legLen

	local function tinted(part: BasePart): BasePart
		part:SetAttribute("Tint", true)
		return part
	end

	tinted(add(ellipsoid(bodySize, primary, bodyMaterial), CFrame.new(), "Body"))
	add(ellipsoid(bodySize * Vector3.new(0.8, 0.65, 0.85), secondary), CFrame.new(0, -0.3 * s, 0), "Belly")

	local headCF = CFrame.new(0, 0.75 * s, -1.55 * s)
	tinted(add(ellipsoid(Vector3.new(1.7, 1.5, 1.6) * s, primary, bodyMaterial), headCF, "Head"))

	for _, x in { -0.42, 0.42 } do
		add(ellipsoid(Vector3.new(0.45, 0.55, 0.3) * s, Color3.new(1, 1, 1)), headCF * CFrame.new(x * s, 0.18 * s, -0.66 * s))
		add(ellipsoid(Vector3.new(0.24, 0.32, 0.2) * s, eyeColor, eyeMaterial), headCF * CFrame.new(x * s, 0.18 * s, -0.78 * s), "Eye")
	end

	local legHeight = legLen + 0.4 * s
	for _, off in { Vector2.new(-0.7, -0.8), Vector2.new(0.7, -0.8), Vector2.new(-0.7, 0.8), Vector2.new(0.7, 0.8) } do
		add(
			newPart(Vector3.new(0.45, legHeight, 0.45) * Vector3.new(s, 1, s), secondary),
			CFrame.new(off.X * s, -hip + legHeight / 2, off.Y * s)
		)
	end

	if fam.Body == "Lizard" then
		tinted(add(ellipsoid(Vector3.new(0.8, 0.7, 2.4) * s, primary, bodyMaterial), CFrame.new(0, -0.1 * s, 2.1 * s) * CFrame.Angles(math.rad(12), 0, 0), "Tail"))
		for i, z in { -0.6, 0.2, 1.0 } do
			local h = (0.75 - i * 0.1) * s
			add(wedge(Vector3.new(0.18 * s, h, 0.7 * s), accent, accentMaterial), CFrame.new(0, bodySize.Y / 2 + h / 2 - 0.15 * s, z * s))
		end
	elseif fam.Body == "Fox" then
		add(ellipsoid(Vector3.new(0.8, 0.6, 0.9) * s, secondary), headCF * CFrame.new(0, -0.25 * s, -0.75 * s), "Snout")
		for _, x in { -0.45, 0.45 } do
			add(wedge(Vector3.new(0.2, 0.75, 0.55) * s, primary), headCF * CFrame.new(x * s, 0.85 * s, 0) * CFrame.Angles(0, math.rad(180), 0))
		end
		local tailCF = CFrame.new(0, 0.4 * s, 2.0 * s) * CFrame.Angles(math.rad(35), 0, 0)
		tinted(add(ellipsoid(Vector3.new(1.0, 1.0, 2.3) * s, primary, bodyMaterial), tailCF, "Tail"))
		local tip = add(ellipsoid(Vector3.new(0.8, 0.8, 0.9) * s, accent, Enum.Material.Neon), tailCF * CFrame.new(0, 0, 1.1 * s), "TailTip")
		local fire = Instance.new("Fire")
		fire.Size = 2 * s
		fire.Heat = 3
		fire.Color = accent
		fire.SecondaryColor = primary
		fire.Parent = tip
	elseif fam.Body == "Wolf" then
		add(newPart(Vector3.new(0.7, 0.55, 0.9) * s, secondary), headCF * CFrame.new(0, -0.25 * s, -0.8 * s), "Snout")
		for _, x in { -0.45, 0.45 } do
			add(wedge(Vector3.new(0.2, 0.9, 0.5) * s, secondary), headCF * CFrame.new(x * s, 0.9 * s, 0.1 * s) * CFrame.Angles(0, math.rad(180), 0))
		end
		add(ellipsoid(Vector3.new(2.0, 1.6, 1.0) * s, secondary), CFrame.new(0, 0.35 * s, -0.9 * s), "Mane")
		tinted(add(ellipsoid(Vector3.new(0.6, 0.6, 2.2) * s, primary, bodyMaterial), CFrame.new(0, 0.1 * s, 2.0 * s) * CFrame.Angles(math.rad(20), 0, 0), "Tail"))
	end

	-- Teen+: back spikes
	if stageIndex >= 2 then
		for i = 1, 3 do
			local z = -0.9 + i * 0.5
			add(wedge(Vector3.new(0.15, 0.55, 0.5) * s, accent, accentMaterial), CFrame.new(0.55 * s, bodySize.Y / 2 - 0.1 * s, z * s) * CFrame.Angles(0, 0, math.rad(-25)))
			add(wedge(Vector3.new(0.15, 0.55, 0.5) * s, accent, accentMaterial), CFrame.new(-0.55 * s, bodySize.Y / 2 - 0.1 * s, z * s) * CFrame.Angles(0, 0, math.rad(25)))
		end
	end

	-- Adult: wings + horns + glow
	if stageIndex >= 3 then
		for _, side in { -1, 1 } do
			local wingCF = CFrame.new(side * 1.1 * s, 0.7 * s, 0.1 * s) * CFrame.Angles(0, 0, math.rad(side * -35))
			tinted(add(newPart(Vector3.new(2.6, 0.15, 1.8) * s, primary, bodyMaterial), wingCF * CFrame.new(side * 1.2 * s, 0, 0), "Wing"))
			add(newPart(Vector3.new(2.2, 0.17, 0.35) * s, accent, accentMaterial), wingCF * CFrame.new(side * 1.2 * s, 0.02 * s, -0.8 * s))
			add(wedge(Vector3.new(0.2, 0.8, 0.35) * s, accent, accentMaterial), headCF * CFrame.new(side * 0.4 * s, 0.9 * s, 0.35 * s) * CFrame.Angles(math.rad(-25), 0, 0))
		end
		local glow = Instance.new("PointLight")
		glow.Color = accent
		glow.Range = 10 * s
		glow.Brightness = 1
		glow.Parent = root
	end

	-- Mutation flair
	if mut then
		particles(root, mut.Color, 0.35 * s, 8)
		if mut.Id == "Celestial" then
			local halo = newPart(Vector3.new(0.15, 1.6 * s, 1.6 * s), Color3.fromRGB(255, 225, 120), Enum.Material.Neon)
			halo.Shape = Enum.PartType.Cylinder
			add(halo, headCF * CFrame.new(0, 1.2 * s, 0) * CFrame.Angles(0, 0, math.rad(90)), "Halo")
			local sparkles = Instance.new("Sparkles")
			sparkles.SparkleColor = Color3.fromRGB(255, 240, 180)
			sparkles.Parent = root
		elseif mut.Id == "Inferno" then
			local fire = Instance.new("Fire")
			fire.Size = 3 * s
			fire.Color = Color3.fromRGB(255, 90, 20)
			fire.SecondaryColor = Color3.fromRGB(255, 220, 60)
			fire.Parent = root
		elseif mut.Id == "Void" then
			particles(root, Color3.fromRGB(20, 0, 40), 0.8 * s, 10, 0.5)
		end
	end

	if record.Aura then
		local aura = CreatureData.Auras[record.Aura]
		if aura then
			local e = particles(root, aura.Color, 0.7 * s, 16, 2)
			e.Name = "Aura"
			local light = Instance.new("PointLight")
			light.Name = "AuraLight"
			light.Color = aura.Color
			light.Range = 8 * s
			light.Brightness = 1.5
			light.Parent = root
		end
	end

	model:SetAttribute("HipHeight", hip)
	model:SetAttribute("Radius", 1.4 * s)
	setTop(model)
	model:SetAttribute("Scale", s)
	return model
end

---------------------------------------------------------------------------------------------------
-- Enemies
---------------------------------------------------------------------------------------------------
function Models.BuildEnemy(typeId: string, variantId: string?): Model
	local data = EnemyData.Types[typeId]
	local variant = EnemyData.Variants[variantId or "Normal"] or EnemyData.Variants.Normal
	local k = variant.Scale or 1
	local body = data.Color
	local eye = data.EyeColor
	if variant.Tint then
		body = body:Lerp(variant.Tint, 0.25)
		eye = variant.Tint
	end
	local dark = body:Lerp(Color3.new(0, 0, 0), 0.4)

	local model, _, add = makeModel(typeId, true)
	local hip, radius

	if data.Shape == "Crawler" then
		local legLen = 0.9 * k
		local size = Vector3.new(3, 1.4, 3.8) * k
		hip = size.Y / 2 + legLen
		radius = 2 * k
		add(ellipsoid(size, body), CFrame.new(), "Body")
		add(ellipsoid(Vector3.new(1.8, 1.1, 1.4) * k, dark), CFrame.new(0, 0.1 * k, -2 * k), "Head")
		for _, x in { -0.45, -0.15, 0.15, 0.45 } do
			add(ellipsoid(Vector3.new(0.25, 0.25, 0.2) * k, eye, Enum.Material.Neon), CFrame.new(x * k, 0.3 * k, -2.65 * k), "Eye")
		end
		for _, z in { -1, 0, 1 } do
			for _, side in { -1, 1 } do
				add(newPart(Vector3.new(2.2 * k, 0.3 * k, 0.3 * k), dark), CFrame.new(side * 1.6 * k, -0.6 * k, z * k) * CFrame.Angles(0, 0, math.rad(side * 35)))
			end
		end
	elseif data.Shape == "Hunter" then
		local legLen = 1.6 * k
		local size = Vector3.new(1.8, 3.2, 1.4) * k
		hip = size.Y / 2 + legLen
		radius = 1.5 * k
		add(newPart(size, body), CFrame.new() * CFrame.Angles(math.rad(-10), 0, 0), "Body")
		add(ellipsoid(Vector3.new(1.6, 1.4, 1.6) * k, dark), CFrame.new(0, 2.2 * k, -0.4 * k), "Head")
		add(ellipsoid(Vector3.new(0.7, 0.7, 0.4) * k, eye, Enum.Material.Neon), CFrame.new(0, 2.25 * k, -1.15 * k), "Eye")
		for _, side in { -1, 1 } do
			add(newPart(Vector3.new(0.4, 3.2, 0.4) * k, dark), CFrame.new(side * 1.2 * k, 0, -0.3 * k) * CFrame.Angles(math.rad(-15), 0, 0))
			add(newPart(Vector3.new(0.5 * k, legLen + 0.5 * k, 0.5 * k), dark), CFrame.new(side * 0.5 * k, -hip + (legLen + 0.5 * k) / 2, 0))
		end
	elseif data.Shape == "Brute" then
		local legLen = 2.2 * k
		local size = Vector3.new(5, 4.5, 3.8) * k
		hip = size.Y / 2 + legLen
		radius = 3 * k
		add(newPart(size, body, Enum.Material.Slate), CFrame.new(), "Body")
		add(newPart(Vector3.new(2.2, 1.8, 2) * k, dark), CFrame.new(0, 2.8 * k, -0.9 * k), "Head")
		for _, x in { -0.5, 0.5 } do
			add(newPart(Vector3.new(0.4, 0.3, 0.2) * k, eye, Enum.Material.Neon), CFrame.new(x * k, 2.95 * k, -1.95 * k), "Eye")
		end
		for _, side in { -1, 1 } do
			add(newPart(Vector3.new(1.8, 4.8, 1.8) * k, body, Enum.Material.Slate), CFrame.new(side * 3.4 * k, -0.6 * k, -0.4 * k), "Arm")
			add(newPart(Vector3.new(1.6 * k, legLen + 0.6 * k, 1.6 * k), dark), CFrame.new(side * 1.3 * k, -hip + (legLen + 0.6 * k) / 2, 0))
		end
	else -- Colossus boss
		local legLen = 6 * k
		local size = Vector3.new(8, 14, 7) * k
		hip = size.Y / 2 + legLen
		radius = 6 * k
		add(newPart(size, body, Enum.Material.Wood), CFrame.new(), "Body")
		add(newPart(Vector3.new(8.4, 3, 7.4) * k, Color3.fromRGB(70, 110, 45), Enum.Material.Grass), CFrame.new(0, 4 * k, 0), "Moss")
		add(newPart(Vector3.new(6, 5, 5.5) * k, dark, Enum.Material.Wood), CFrame.new(0, 9 * k, -0.6 * k), "Head")
		for _, x in { -1.4, 1.4 } do
			add(ellipsoid(Vector3.new(1.2, 0.9, 0.4) * k, eye, Enum.Material.Neon), CFrame.new(x * k, 9.6 * k, -3.4 * k), "Eye")
		end
		local core = add(ellipsoid(Vector3.new(2.8, 2.8, 1.2) * k, Color3.fromRGB(60, 90, 40), Enum.Material.SmoothPlastic), CFrame.new(0, 1 * k, -3.6 * k), "Core")
		local coreLight = Instance.new("PointLight")
		coreLight.Name = "CoreLight"
		coreLight.Color = eye
		coreLight.Range = 0
		coreLight.Brightness = 4
		coreLight.Parent = core
		for _, side in { -1, 1 } do
			add(newPart(Vector3.new(3, 12, 3) * k, body, Enum.Material.Wood), CFrame.new(side * 5.6 * k, -1.5 * k, -0.5 * k) * CFrame.Angles(0, 0, math.rad(side * 8)), "Arm")
			add(newPart(Vector3.new(3.2 * k, legLen + 1 * k, 3.2 * k), dark, Enum.Material.Wood), CFrame.new(side * 2.4 * k, -hip + (legLen + 1 * k) / 2, 0))
			add(newPart(Vector3.new(1, 6, 1) * k, dark, Enum.Material.Wood), CFrame.new(side * 2 * k, 13 * k, 0) * CFrame.Angles(0, 0, math.rad(side * -30)))
		end
	end

	model:SetAttribute("HipHeight", hip)
	model:SetAttribute("Radius", radius)
	setTop(model)
	return model
end

---------------------------------------------------------------------------------------------------
-- Eggs
---------------------------------------------------------------------------------------------------
function Models.BuildEgg(eggId: string): Model
	local egg = EggData[eggId] or EggData.ForestEgg
	local model, root, add = makeModel(eggId, false)
	add(ellipsoid(Vector3.new(2, 2.6, 2), egg.Color), CFrame.new(), "Shell")

	local spotMaterial = if egg.NeonSpots then Enum.Material.Neon else Enum.Material.SmoothPlastic
	local spots = { { 0, 0.5 }, { 1.3, -0.1 }, { 2.5, 0.35 }, { 3.7, -0.4 }, { 4.9, 0.15 }, { 5.8, 0.7 } }
	for _, spot in spots do
		local a, y = spot[1], spot[2]
		local r = math.sqrt(math.max(0, 1 - (y / 1.3) ^ 2)) * 0.97
		local pos = Vector3.new(r * math.cos(a), y, r * math.sin(a))
		add(ellipsoid(Vector3.new(0.55, 0.45, 0.2), egg.SpotColor, spotMaterial), CFrame.lookAt(pos, pos * 2))
	end

	local light = Instance.new("PointLight")
	light.Color = egg.Color
	light.Range = 10
	light.Brightness = 1.5
	light.Parent = root

	model:SetAttribute("HipHeight", 1.3)
	model:SetAttribute("Radius", 1)
	return model
end

return Models
]=])
make(n3, "ModuleScript", "Net", [=[
-- All remotes live in ReplicatedStorage.HatchOrDie.Remotes and are created by the server.
local RunService = game:GetService("RunService")

local Root = script.Parent.Parent

local Net = {}

Net.Events = {
	-- client -> server
	"ClientReady",
	"RequestHatch",
	"EquipCreature",
	"FeedCreature",
	"SetCommand",
	"SetTarget",
	"UseAbility",
	"EvolveCreature",
	"ReleaseCreature",
	"ToggleLock",
	"EquipAura",
	"BuyItem",
	-- server -> client
	"SyncData",
	"HatchResult",
	"Evolved",
	"Notify",
	"Announce",
	"BossBar",
	"OpenPanel",
	"NightResult",
	"Effect",
}

local folder: Folder? = nil

local function getFolder(): Folder
	if folder then
		return folder
	end
	if RunService:IsServer() then
		local f = Root:FindFirstChild("Remotes")
		if not f then
			f = Instance.new("Folder")
			f.Name = "Remotes"
			f.Parent = Root
		end
		for _, name in Net.Events do
			if not f:FindFirstChild(name) then
				local remote = Instance.new("RemoteEvent")
				remote.Name = name
				remote.Parent = f
			end
		end
		folder = f
	else
		folder = Root:WaitForChild("Remotes")
	end
	return folder :: Folder
end

function Net.Get(name: string): RemoteEvent
	local f = getFolder()
	if RunService:IsServer() then
		return f:FindFirstChild(name) :: RemoteEvent
	end
	return f:WaitForChild(name) :: RemoteEvent
end

-- Server-side handler with a per-player rate limit and error isolation.
function Net.On(name: string, handler: (Player, ...any) -> (), cooldown: number?)
	local remote = Net.Get(name)
	local last = setmetatable({}, { __mode = "k" })
	remote.OnServerEvent:Connect(function(player, ...)
		local now = os.clock()
		if cooldown and last[player] and now - last[player] < cooldown then
			return
		end
		last[player] = now
		local ok, err = pcall(handler, player, ...)
		if not ok then
			warn(("[Net] %s failed for %s: %s"):format(name, player.Name, tostring(err)))
		end
	end)
end

function Net.Notify(player: Player, text: string, color: Color3?)
	Net.Get("Notify"):FireClient(player, text, color)
end

function Net.NotifyAll(text: string, color: Color3?)
	Net.Get("Notify"):FireAllClients(text, color)
end

function Net.Announce(text: string, color: Color3?, big: boolean?)
	Net.Get("Announce"):FireAllClients(text, color, big)
end

return Net
]=])
make(n3, "ModuleScript", "Signal", [=[
-- Minimal signal that passes tables by reference (BindableEvents deep-copy them).
local Signal = {}
Signal.__index = Signal

function Signal.new()
	return setmetatable({ _handlers = {} }, Signal)
end

function Signal:Connect(fn)
	local handler = { Fn = fn, Connected = true }
	table.insert(self._handlers, handler)
	return {
		Disconnect = function()
			handler.Connected = false
			local i = table.find(self._handlers, handler)
			if i then
				table.remove(self._handlers, i)
			end
		end,
	}
end

function Signal:Fire(...)
	for _, handler in table.clone(self._handlers) do
		if handler.Connected then
			task.spawn(handler.Fn, ...)
		end
	end
end

return Signal
]=])
end
print("✅ HATCH OR DIE Part 2/4 done. Now run Part 3.")
