-- HATCH OR DIE - installer PART 4 of 4: CLIENT CODE (StarterPlayerScripts)
-- Generated by tools/build_installer.py from src/. Do not edit by hand.
-- Paste everything into the Roblox Studio command bar and press Enter.
local function make(parent, className, name, source)
	local existing = parent:FindFirstChild(name)
	if existing then
		existing:Destroy()
	end
	local inst = Instance.new(className)
	inst.Name = name
	if source then
		inst.Source = source
	end
	inst.Parent = parent
	return inst
end

local n1 = make(game:GetService("StarterPlayer"):WaitForChild("StarterPlayerScripts"), "LocalScript", "HatchOrDieClient", [=[
-- HATCH OR DIE client entry. The client only renders and sends intents; the server decides outcomes.
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UserInputService = game:GetService("UserInputService")
local SoundService = game:GetService("SoundService")

local player = Players.LocalPlayer
local Root = ReplicatedStorage:WaitForChild("HatchOrDie")

local Net = require(Root.Shared.Net)
local Signal = require(Root.Shared.Signal)
local Models = require(Root.Shared.Models)
local GameConfig = require(Root.Config.GameConfig)
local CreatureData = require(Root.Config.CreatureData)
local EggData = require(Root.Config.EggData)
local ShopData = require(Root.Config.ShopData)
local Rarity = require(Root.Config.Rarity)

local UIKit = require(script.UIKit)
local Layout = require(script.Layout)
local Hud = require(script.Hud)
local Panels = require(script.Panels)
local Cinematics = require(script.Cinematics)

local gui = Layout.Obtain(player)

local ctx = {
	Root = Root,
	Net = Net,
	Gui = gui,
	Models = Models,
	GameConfig = GameConfig,
	CreatureData = CreatureData,
	EggData = EggData,
	ShopData = ShopData,
	Rarity = Rarity,
	Layout = Layout,
	Profile = nil,
	SavingEnabled = true,
	ProfileChanged = Signal.new(),
	Hud = Hud,
	Panels = Panels,
	Cinematics = Cinematics,
}

function ctx.SlotLimit(): number
	local bonus = if player:GetAttribute("Pass_ExtraSlots") then GameConfig.ExtraSlotsBonus else 0
	return GameConfig.BaseCreatureSlots + bonus
end

Hud.Init(ctx)
Panels.Init(ctx)
Cinematics.Init(ctx)

---------------------------------------------------------------------------------------------------
-- Server -> client
---------------------------------------------------------------------------------------------------
local warnedNoSave = false
Net.Get("SyncData").OnClientEvent:Connect(function(profile, savingEnabled)
	ctx.Profile = profile
	ctx.SavingEnabled = savingEnabled
	ctx.ProfileChanged:Fire(profile)
	if not savingEnabled and not warnedNoSave then
		warnedNoSave = true
		Hud.Toast("⚠️ Saving is OFF (Studio test or DataStores unavailable).", Color3.fromRGB(255, 170, 60))
	end
end)

Net.Get("Notify").OnClientEvent:Connect(function(text, color)
	Hud.Toast(text, color)
end)

Net.Get("Announce").OnClientEvent:Connect(function(text, color, big)
	Hud.Announce(text, color, big)
	if big then
		Cinematics.Shake(0.6, 0.4)
	end
end)

Net.Get("HatchResult").OnClientEvent:Connect(function(result)
	if Panels.IsOpen() then
		Panels.Close()
	end
	Cinematics.Hatch(result)
end)

Net.Get("Evolved").OnClientEvent:Connect(function(result)
	if Panels.IsOpen() then
		Panels.Close()
	end
	Cinematics.Evolve(result)
end)

Net.Get("BossBar").OnClientEvent:Connect(function(data)
	Hud.SetBoss(data)
end)

Net.Get("OpenPanel").OnClientEvent:Connect(function(name)
	Panels.Open(name)
end)

Net.Get("NightResult").OnClientEvent:Connect(function(result)
	Hud.ShowNightResult(result)
end)

Net.Get("Effect").OnClientEvent:Connect(function(kind, value)
	if kind == "Shake" then
		Cinematics.Shake(value or 1, 0.5)
	end
end)

---------------------------------------------------------------------------------------------------
-- Death overlay
---------------------------------------------------------------------------------------------------
local function onCharacter(character: Model)
	Hud.SetDead(false)
	local humanoid = character:WaitForChild("Humanoid") :: Humanoid
	humanoid.Died:Connect(function()
		if Root:GetAttribute("Phase") == "Night" then
			Hud.SetDead(true)
		end
	end)
end
player.CharacterAdded:Connect(onCharacter)
if player.Character then
	task.spawn(onCharacter, player.Character)
end

---------------------------------------------------------------------------------------------------
-- Input: Q ability, F feed, 1/2/3 commands, click/tap an enemy to target it
---------------------------------------------------------------------------------------------------
local targetHighlight = UIKit.new("Highlight", {
	FillTransparency = 1,
	OutlineColor = Color3.fromRGB(255, 220, 60),
	DepthMode = Enum.HighlightDepthMode.AlwaysOnTop,
	Parent = workspace,
})
local highlightToken = 0

local function tryTarget(screenPosition: Vector2)
	local camera = workspace.CurrentCamera
	local enemies = workspace:FindFirstChild("Enemies")
	if not camera or not enemies then
		return
	end
	local ray = camera:ScreenPointToRay(screenPosition.X, screenPosition.Y)
	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Include
	params.FilterDescendantsInstances = { enemies }
	local hit = workspace:Raycast(ray.Origin, ray.Direction * 400, params)
	if not hit then
		return
	end
	local model = hit.Instance:FindFirstAncestorOfClass("Model")
	while model and model.Parent ~= enemies do
		model = model.Parent and model.Parent:FindFirstAncestorOfClass("Model")
	end
	if not model then
		return
	end
	Net.Get("SetTarget"):FireServer(model)
	targetHighlight.Adornee = model
	highlightToken += 1
	local token = highlightToken
	task.delay(2.5, function()
		if highlightToken == token then
			targetHighlight.Adornee = nil
		end
	end)
end

local KEY_ACTIONS = {
	[Enum.KeyCode.Q] = function()
		Net.Get("UseAbility"):FireServer()
	end,
	[Enum.KeyCode.F] = function()
		Net.Get("FeedCreature"):FireServer()
	end,
	[Enum.KeyCode.One] = function()
		Net.Get("SetCommand"):FireServer("Follow")
	end,
	[Enum.KeyCode.Two] = function()
		Net.Get("SetCommand"):FireServer("Attack")
	end,
	[Enum.KeyCode.Three] = function()
		Net.Get("SetCommand"):FireServer("Defend")
	end,
}

UserInputService.InputBegan:Connect(function(input, processed)
	if processed then
		return
	end
	if input.UserInputType == Enum.UserInputType.Keyboard then
		local action = KEY_ACTIONS[input.KeyCode]
		if action then
			action()
		end
	elseif input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
		tryTarget(Vector2.new(input.Position.X, input.Position.Y))
	end
end)

---------------------------------------------------------------------------------------------------
-- Optional music (set ids in GameConfig.Music)
---------------------------------------------------------------------------------------------------
local music = UIKit.new("Sound", { Looped = true, Volume = 0.35, Parent = SoundService })
local function updateMusic()
	local phase = Root:GetAttribute("Phase")
	local id = if phase == "Night" then GameConfig.Music.Night else GameConfig.Music.Day
	if id == "" then
		music:Stop()
		return
	end
	if music.SoundId ~= id then
		music.SoundId = id
		music:Play()
	end
end
Root:GetAttributeChangedSignal("Phase"):Connect(updateMusic)
updateMusic()

---------------------------------------------------------------------------------------------------
-- VIP chat tag
---------------------------------------------------------------------------------------------------
local TextChatService = game:GetService("TextChatService")
TextChatService.OnIncomingMessage = function(message)
	local props = Instance.new("TextChatMessageProperties")
	local source = message.TextSource
	if source then
		local speaker = Players:GetPlayerByUserId(source.UserId)
		if speaker and speaker:GetAttribute("Pass_VIP") then
			props.PrefixText = "<font color='#FFD23C'>[VIP]</font> " .. message.PrefixText
		end
	end
	return props
end

Net.Get("ClientReady"):FireServer()
]=])
make(n1, "ModuleScript", "Cinematics", [=[
-- Hatch and evolution reveals, plus camera shake. Reveals are queued so they never overlap.
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local SoundService = game:GetService("SoundService")

local UIKit = require(script.Parent.UIKit)

local Cinematics = {}

local player = Players.LocalPlayer
local C = UIKit.Colors

local ctx
local gui: ScreenGui
local queue = {}
local running = false

local function playSound(id: string?, volume: number?)
	if not id or id == "" then
		return
	end
	local sound = Instance.new("Sound")
	sound.SoundId = id
	sound.Volume = volume or 0.6
	sound.Parent = SoundService
	sound:Play()
	sound.Ended:Connect(function()
		sound:Destroy()
	end)
	task.delay(10, function()
		if sound.Parent then
			sound:Destroy()
		end
	end)
end

function Cinematics.Shake(intensity: number, duration: number?)
	local character = player.Character
	local humanoid = character and character:FindFirstChildOfClass("Humanoid")
	if not humanoid then
		return
	end
	local d = duration or 0.45
	local start = os.clock()
	local connection
	connection = RunService.RenderStepped:Connect(function()
		local t = os.clock() - start
		if t >= d or not humanoid.Parent then
			humanoid.CameraOffset = Vector3.zero
			connection:Disconnect()
			return
		end
		local falloff = 1 - t / d
		local k = intensity * falloff
		humanoid.CameraOffset = Vector3.new((math.random() - 0.5) * k, (math.random() - 0.5) * k, (math.random() - 0.5) * k)
	end)
end

local function overlay()
	local root = UIKit.new("Frame", {
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = Color3.new(0, 0, 0),
		BackgroundTransparency = 1,
		Active = true,
		Parent = gui,
	})
	UIKit.tween(root, 0.3, { BackgroundTransparency = 0.3 })

	local rays = UIKit.new("Frame", {
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.45),
		Size = UDim2.fromScale(0.97, 0.97),
		SizeConstraint = Enum.SizeConstraint.RelativeYY,
		BackgroundColor3 = Color3.new(1, 1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Parent = root,
	})
	UIKit.new("UICorner", { CornerRadius = UDim.new(1, 0), Parent = rays })
	local gradient = UIKit.new("UIGradient", {
		Transparency = NumberSequence.new({
			NumberSequenceKeypoint.new(0, 0.3),
			NumberSequenceKeypoint.new(0.5, 0.85),
			NumberSequenceKeypoint.new(1, 0.3),
		}),
		Parent = rays,
	})

	local vp = UIKit.viewport({
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.42),
		Size = UDim2.fromScale(0.47, 0.47),
		SizeConstraint = Enum.SizeConstraint.RelativeYY,
		Parent = root,
	}, nil, false)

	local title = UIKit.text({
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.fromScale(0.5, 0.665),
		Size = UDim2.fromScale(0.8, 0.078),
		Font = Enum.Font.FredokaOne,
		TextStrokeTransparency = 0,
		Parent = root,
	})
	local sub = UIKit.text({
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.fromScale(0.5, 0.745),
		Size = UDim2.fromScale(0.7, 0.042),
		Font = Enum.Font.FredokaOne,
		TextColor3 = C.SubText,
		Parent = root,
	})
	local tag = UIKit.text({
		AnchorPoint = Vector2.new(0.5, 1),
		Position = UDim2.fromScale(0.5, 0.18),
		Size = UDim2.fromScale(0.6, 0.05),
		Font = Enum.Font.FredokaOne,
		TextColor3 = C.Gold,
		Parent = root,
	})
	local flash = UIKit.new("Frame", {
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = Color3.new(1, 1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ZIndex = 10,
		Parent = root,
	})
	return {
		Root = root,
		Rays = rays,
		Gradient = gradient,
		Viewport = vp,
		Title = title,
		Sub = sub,
		Tag = tag,
		Flash = flash,
	}
end

local function spinRays(o, color: Color3)
	o.Rays.BackgroundColor3 = color
	o.Rays.BackgroundTransparency = 0
	local connection
	connection = RunService.RenderStepped:Connect(function(dt)
		if not o.Root.Parent then
			connection:Disconnect()
			return
		end
		o.Gradient.Rotation = (o.Gradient.Rotation + dt * 60) % 360
	end)
end

local function waitForDismiss(o, seconds: number)
	local done = false
	local button = UIKit.button({
		AnchorPoint = Vector2.new(0.5, 1),
		Position = UDim2.fromScale(0.5, 0.95),
		Size = UDim2.fromScale(0.3, 0.067),
		SizeConstraint = Enum.SizeConstraint.RelativeYY,
		BackgroundColor3 = Color3.fromRGB(70, 170, 90),
		Text = "AWESOME!",
		Parent = o.Root,
	}, function()
		done = true
	end)
	local deadline = os.clock() + seconds
	while not done and os.clock() < deadline do
		task.wait(0.05)
	end
	button:Destroy()
	UIKit.tween(o.Root, 0.25, { BackgroundTransparency = 1 })
	for _, d in o.Root:GetDescendants() do
		if d:IsA("GuiObject") then
			d.Visible = false
		end
	end
	task.wait(0.25)
	o.Root:Destroy()
end

local function describe(record)
	local CD = ctx.CreatureData
	local rarity = CD.GetRarity(record)
	local color = ctx.Rarity.Colors[rarity]
	local mutationText = ""
	if record.Mutation then
		mutationText = ("🧬 %s MUTATION!"):format(record.Mutation:upper())
	end
	return rarity, color, mutationText
end

local function playHatch(result)
	local o = overlay()
	local egg = ctx.EggData[result.EggId]
	local record = result.Creature
	local rarity, color, mutationText = describe(record)
	local rare = ctx.Rarity.AtLeast(rarity, "Epic")

	local eggModel = ctx.Models.BuildEgg(result.EggId)
	UIKit.setViewportModel(o.Viewport, eggModel)
	o.Title.Text = "HATCHING..."
	o.Title.TextColor3 = C.Text
	o.Sub.Text = if egg then egg.Name else ""

	local shakes = if rare then 5 else 3
	for i = 1, shakes do
		local amount = 6 + i * 5
		for j = 1, 6 do
			local angle = math.rad(if j % 2 == 0 then amount else -amount)
			eggModel:PivotTo(CFrame.Angles(0, 0, angle))
			task.wait(0.04)
		end
		eggModel:PivotTo(CFrame.new())
		o.Flash.BackgroundTransparency = 0.8
		UIKit.tween(o.Flash, 0.2, { BackgroundTransparency = 1 })
		if i == shakes - 1 and rare then
			spinRays(o, color)
			o.Tag.Text = "✨ SOMETHING RARE... ✨"
		end
		task.wait(0.28)
	end

	playSound(ctx.GameConfig.Sounds.Hatch, 0.8)
	o.Flash.BackgroundTransparency = 0
	UIKit.tween(o.Flash, 0.7, { BackgroundTransparency = 1 })
	if not rare then
		spinRays(o, color)
	end
	local creatureModel = ctx.Models.BuildCreature(record)
	UIKit.setViewportModel(o.Viewport, creatureModel)
	local spin = 0
	local connection
	connection = RunService.RenderStepped:Connect(function(dt)
		if not creatureModel.Parent then
			connection:Disconnect()
			return
		end
		spin += dt
		creatureModel:PivotTo(CFrame.Angles(0, spin, 0))
	end)

	o.Title.Text = ctx.CreatureData.GetDisplayName(record)
	o.Title.TextColor3 = color
	o.Title.Size = UDim2.fromScale(0.8, 0.125)
	UIKit.tween(o.Title, 0.4, { Size = UDim2.fromScale(0.8, 0.078) }, Enum.EasingStyle.Back)
	o.Sub.Text = rarity:upper() .. (if mutationText ~= "" then "  •  " .. mutationText else "")
	o.Sub.TextColor3 = color
	o.Tag.Text = if result.IsNew then "🆕 NEW DISCOVERY!" else ""
	if rare then
		Cinematics.Shake(1.2, 0.6)
	end
	waitForDismiss(o, 7)
end

local function playEvolve(result)
	local o = overlay()
	local record = result.Creature
	local rarity, color, mutationText = describe(record)

	local before = table.clone(record)
	before.Stage = math.max(1, record.Stage - 1)
	if result.Mutated then
		before.Mutation = nil
	end
	local model = ctx.Models.BuildCreature(before)
	UIKit.setViewportModel(o.Viewport, model)
	o.Title.Text = result.FromName .. " is evolving..."
	o.Title.TextColor3 = C.Text
	spinRays(o, C.Gold)

	for i = 1, 4 do
		o.Flash.BackgroundTransparency = 0.3
		UIKit.tween(o.Flash, 0.35 - i * 0.05, { BackgroundTransparency = 1 })
		task.wait(0.5 - i * 0.08)
	end
	playSound(ctx.GameConfig.Sounds.Hatch, 0.9)
	o.Flash.BackgroundTransparency = 0
	UIKit.tween(o.Flash, 0.8, { BackgroundTransparency = 1 })
	UIKit.setViewportModel(o.Viewport, ctx.Models.BuildCreature(record))
	o.Rays.BackgroundColor3 = color
	Cinematics.Shake(1, 0.5)

	o.Tag.Text = if result.Mutated then "🧬 IT MUTATED!" else "✨ EVOLVED! ✨"
	o.Title.Text = ctx.CreatureData.GetDisplayName(record)
	o.Title.TextColor3 = color
	o.Sub.Text = rarity:upper() .. " • " .. ctx.CreatureData.Stages[record.Stage].Name:upper() .. (if mutationText ~= "" then "  •  " .. mutationText else "")
	o.Sub.TextColor3 = color
	waitForDismiss(o, 6)
end

local function pump()
	if running then
		return
	end
	running = true
	while #queue > 0 do
		local item = table.remove(queue, 1)
		local ok, err = pcall(item.Fn, item.Data)
		if not ok then
			warn("[Cinematics] " .. tostring(err))
		end
	end
	running = false
end

function Cinematics.Hatch(result)
	table.insert(queue, { Fn = playHatch, Data = result })
	task.spawn(pump)
end

function Cinematics.Evolve(result)
	table.insert(queue, { Fn = playEvolve, Data = result })
	task.spawn(pump)
end

function Cinematics.Init(context)
	ctx = context
	gui = UIKit.new("ScreenGui", {
		Name = "HatchOrDieCinematics",
		ResetOnSpawn = false,
		IgnoreGuiInset = true,
		ScreenInsets = Enum.ScreenInsets.DeviceSafeInsets,
		DisplayOrder = 10,
		Parent = player:WaitForChild("PlayerGui"),
	})
end

return Cinematics
]=])
make(n1, "ModuleScript", "Hud", [=[
-- Always-on HUD: phase banner + timer, objective, currencies, creature card, commands,
-- ability/feed buttons, menu bar, incubator timer, toasts, announcements, boss bar.
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

local UIKit = require(script.Parent.UIKit)

local Hud = {}

local player = Players.LocalPlayer
local C = UIKit.Colors

local ctx
local refs = {}
local lastPhaseKey = ""
local bossState = nil

local function serverNow(): number
	return workspace:GetServerTimeNow()
end

---------------------------------------------------------------------------------------------------
-- Bind: find every element by name (built-in Layout or the designer's StarterGui.HatchOrDieUI)
---------------------------------------------------------------------------------------------------
local baseSizes = {}
local modeColors = {}
local toastTemplate: GuiObject? = nil

local function bind(gui: ScreenGui)
	local find = ctx.Layout.Finder(gui)
	for _, name in {
		"PhaseBanner", "PhaseTitle", "PhaseSub", "Objective", "BossBar", "BossName", "BossFill",
		"Coins", "Berries", "Best", "CreatureCard", "CreatureName", "CreatureStage", "CreatureHPFill",
		"CreatureHPText", "CreatureXPFill", "CreatureXPText", "EvolveButton", "FeedButton", "AbilityButton",
		"AbilityCooldown", "EggBadge", "Incubator", "IncubatorText", "IncubatorFill", "Toasts",
		"Announcement", "BigTitle", "BigSub", "NightResult", "ResultTitle", "ResultBody", "DeathOverlay",
	} do
		refs[name] = find(name)
	end
	refs.BannerGradient = refs.PhaseBanner:FindFirstChildOfClass("UIGradient")
	refs.ModeButtons = {}
	for _, mode in { "Follow", "Attack", "Defend" } do
		local button = find("Mode" .. mode)
		refs.ModeButtons[mode] = button
		modeColors[button] = button.BackgroundColor3
	end
	refs.MenuButtons = {}
	for _, name in { "Eggs", "Creatures", "Shop" } do
		refs.MenuButtons[name] = find("Menu" .. name)
	end
	local template = gui:FindFirstChild("ToastTemplate", true)
	if template and template:IsA("GuiObject") then
		toastTemplate = template
		template.Visible = false
	end
	for _, name in { "Announcement", "BigTitle", "NightResult" } do
		baseSizes[name] = refs[name].Size
	end
	ctx.Layout.MakeResponsive(gui)

	-- Behavior
	local function onClick(button, fn)
		UIKit.decorate(button)
		button.Activated:Connect(fn)
	end
	onClick(refs.EvolveButton, function()
		local profile = ctx.Profile
		if profile and profile.Equipped then
			ctx.Net.Get("EvolveCreature"):FireServer(profile.Equipped)
		end
	end)
	for mode, button in refs.ModeButtons do
		onClick(button, function()
			ctx.Net.Get("SetCommand"):FireServer(mode)
		end)
	end
	onClick(refs.FeedButton, function()
		ctx.Net.Get("FeedCreature"):FireServer()
	end)
	onClick(refs.AbilityButton, function()
		ctx.Net.Get("UseAbility"):FireServer()
	end)
	for name, button in refs.MenuButtons do
		onClick(button, function()
			ctx.Panels.Toggle(name)
		end)
	end

	-- Start states (exported layouts are saved fully visible so they're easy to edit)
	refs.BossBar.Visible = false
	refs.CreatureCard.Visible = false
	refs.EvolveButton.Visible = false
	refs.EggBadge.Visible = false
	refs.Incubator.Visible = false
	refs.NightResult.Visible = false
	refs.DeathOverlay.Visible = false
	for _, name in { "Announcement", "BigTitle", "BigSub" } do
		refs[name].TextTransparency = 1
		refs[name].TextStrokeTransparency = 1
	end
end

---------------------------------------------------------------------------------------------------
-- Public messaging
---------------------------------------------------------------------------------------------------
function Hud.Toast(text: string, color: Color3?)
	local toast, label
	if toastTemplate then
		toast = toastTemplate:Clone()
		toast.Visible = true
		label = toast:FindFirstChild("Label", true) or toast
		toast.Parent = refs.Toasts
	else
		toast = UIKit.panel({ Size = UDim2.fromScale(1, 0.19), BackgroundColor3 = C.Bg, Parent = refs.Toasts })
		label = UIKit.text({ Position = UDim2.fromScale(0.03, 0.12), Size = UDim2.fromScale(0.94, 0.76), TextXAlignment = Enum.TextXAlignment.Left, Parent = toast })
	end
	if label:IsA("TextLabel") or label:IsA("TextButton") then
		label.Text = text
		if color then
			label.TextColor3 = color
		end
	end
	local frames = {}
	for _, child in refs.Toasts:GetChildren() do
		if child:IsA("GuiObject") then
			table.insert(frames, child)
		end
	end
	if #frames > 4 then
		frames[1]:Destroy()
	end
	task.delay(4.5, function()
		if toast.Parent then
			for _, d in toast:GetDescendants() do
				if d:IsA("TextLabel") or d:IsA("TextButton") then
					UIKit.tween(d, 0.4, { TextTransparency = 1, TextStrokeTransparency = 1 })
				end
			end
			UIKit.tween(toast, 0.4, { BackgroundTransparency = 1 })
			task.wait(0.4)
			toast:Destroy()
		end
	end)
end

local announceToken = 0
function Hud.Announce(text: string, color: Color3?, big: boolean?)
	announceToken += 1
	local token = announceToken
	local label = refs.Announcement
	label.Text = text
	label.TextColor3 = color or C.Gold
	label.Size = if big then UIKit.scaleUDim2(baseSizes.Announcement, 1.35) else baseSizes.Announcement
	label.TextTransparency = 0
	label.TextStrokeTransparency = 0.1
	if big then
		label.Rotation = -3
		UIKit.tween(label, 0.4, { Rotation = 0 }, Enum.EasingStyle.Elastic)
	end
	task.delay(if big then 5 else 4, function()
		if announceToken == token then
			UIKit.tween(label, 0.6, { TextTransparency = 1, TextStrokeTransparency = 1 })
		end
	end)
end

local titleToken = 0
function Hud.BigTitle(title: string, sub: string, color: Color3)
	titleToken += 1
	local token = titleToken
	refs.BigTitle.Text = title
	refs.BigTitle.TextColor3 = color
	refs.BigSub.Text = sub
	refs.BigTitle.TextTransparency = 1
	refs.BigSub.TextTransparency = 1
	refs.BigTitle.Size = UIKit.scaleUDim2(baseSizes.BigTitle, 1.5)
	UIKit.tween(refs.BigTitle, 0.5, { TextTransparency = 0, TextStrokeTransparency = 0, Size = baseSizes.BigTitle }, Enum.EasingStyle.Back)
	UIKit.tween(refs.BigSub, 0.8, { TextTransparency = 0, TextStrokeTransparency = 0.2 })
	task.delay(3, function()
		if titleToken == token then
			UIKit.tween(refs.BigTitle, 0.7, { TextTransparency = 1, TextStrokeTransparency = 1 })
			UIKit.tween(refs.BigSub, 0.7, { TextTransparency = 1, TextStrokeTransparency = 1 })
		end
	end)
end

function Hud.ShowNightResult(result)
	local lines = {}
	if result.Wipe then
		refs.ResultTitle.Text = ("☠️ NIGHT %d CLAIMED EVERYONE"):format(result.Night)
		refs.ResultTitle.TextColor3 = C.Bad
		table.insert(lines, "The run resets to Night 1.")
		table.insert(lines, "Your creatures, eggs and coins are safe.")
		table.insert(lines, "Evolve, hatch stronger eggs, and try again!")
	elseif result.Survived then
		refs.ResultTitle.Text = ("☀️ NIGHT %d SURVIVED!"):format(result.Night)
		refs.ResultTitle.TextColor3 = C.Gold
		table.insert(lines, ("🪙 +%d coins"):format(result.Coins or 0))
		table.insert(lines, ("✨ +%d creature XP"):format(result.XP or 0))
		table.insert(lines, ("🍓 +%d berries"):format(result.Berries or 0))
		for _, eggId in result.Eggs or {} do
			local egg = ctx.EggData[eggId]
			table.insert(lines, "🥚 " .. (if egg then egg.Name else eggId))
		end
	else
		refs.ResultTitle.Text = "💀 YOU FELL LAST NIGHT"
		refs.ResultTitle.TextColor3 = C.Bad
		table.insert(lines, "No rewards this time.")
		table.insert(lines, "Stay close to your creature and feed it when it's hurt.")
	end
	refs.ResultBody.Text = table.concat(lines, "\n")
	refs.NightResult.Visible = true
	refs.NightResult.Size = UIKit.scaleUDim2(baseSizes.NightResult, 0.8)
	UIKit.tween(refs.NightResult, 0.35, { Size = baseSizes.NightResult }, Enum.EasingStyle.Back)
	task.delay(5, function()
		refs.NightResult.Visible = false
	end)
end

function Hud.SetBoss(data)
	bossState = data
	refs.BossBar.Visible = data ~= nil
	if data then
		refs.BossName.Text = data.Name .. (if data.Enraged then "  🔥 ENRAGED" else "") .. (if data.Exposed then "  💥 CORE EXPOSED" else "")
		refs.BossFill.BackgroundColor3 = if data.Exposed then Color3.fromRGB(255, 220, 60) else Color3.fromRGB(220, 50, 50)
		UIKit.tween(refs.BossFill, 0.15, { Size = UDim2.fromScale(math.clamp(data.Health / data.MaxHealth, 0, 1), 1) })
	end
end

---------------------------------------------------------------------------------------------------
-- Refresh
---------------------------------------------------------------------------------------------------
local function equippedRecord(profile)
	if not profile or not profile.Equipped then
		return nil
	end
	for _, record in profile.Creatures do
		if record.Id == profile.Equipped then
			return record
		end
	end
	return nil
end

local function objectiveText(profile): string
	if not profile then
		return "Loading..."
	end
	local phase = ctx.Root:GetAttribute("Phase")
	local record = equippedRecord(profile)
	if #profile.Creatures == 0 then
		if profile.Incubator then
			return "🥚 Your first egg is hatching... get ready!"
		elseif #profile.Eggs > 0 then
			return "🥚 Open Eggs and hatch an egg!"
		end
		return "🥚 Find an egg in the forest!"
	end
	if player:GetAttribute("CreatureKO") then
		return "💫 Your creature is down! Feed it a berry [F] to revive it"
	end
	if record and ctx.CreatureData.CanEvolve(record) then
		return "✨ Your creature can EVOLVE! Tap Evolve"
	end
	if phase == "Night" then
		if bossState then
			return "⚠️ Dodge the red zones! Hit the glowing core after a slam"
		end
		return "🌙 Survive until morning! Click enemies to send your creature"
	end
	local remaining = (ctx.Root:GetAttribute("PhaseEndsAt") or 0) - serverNow()
	if remaining < 12 then
		return "⚠️ Night is coming! Stay near camp and your creature"
	end
	if profile.Berries == 0 then
		return "🍓 Pick berries in the forest - they feed and heal your creature"
	end
	if profile.Incubator == nil and #profile.Eggs > 0 then
		return "🥚 You have an egg waiting - open Eggs to hatch it"
	end
	if record then
		local stage = ctx.CreatureData.Stages[record.Stage]
		if stage and stage.XPToEvolve and record.XP < stage.XPToEvolve then
			return "Feed your creature [F] and explore the Cave, Ruins and Cabin for eggs"
		end
	end
	return "Explore for eggs and crystals before nightfall"
end

function Hud.RefreshProfile()
	local profile = ctx.Profile
	if not profile then
		return
	end
	refs.Coins.Text = "🪙 " .. UIKit.formatNumber(profile.Coins)
	refs.Berries.Text = "🍓 " .. profile.Berries
	refs.Best.Text = "🏆 Best: Night " .. profile.HighestNight

	local eggCount = #profile.Eggs
	refs.EggBadge.Visible = eggCount > 0
	refs.EggBadge.Text = tostring(eggCount)

	local record = equippedRecord(profile)
	refs.CreatureCard.Visible = record ~= nil
	if record then
		local CD = ctx.CreatureData
		local rarity = CD.GetRarity(record)
		refs.CreatureName.Text = UIKit.FamilyIcons[record.Family] .. " " .. CD.GetDisplayName(record)
		refs.CreatureName.TextColor3 = ctx.Rarity.Colors[rarity]
		local stage = CD.Stages[record.Stage]
		refs.CreatureStage.Text = ("%s • %s • Stage %d/%d"):format(rarity, stage.Name, record.Stage, #CD.Stages)
		if stage.XPToEvolve then
			refs.CreatureXPFill.Size = UDim2.fromScale(math.clamp(record.XP / stage.XPToEvolve, 0, 1), 1)
			refs.CreatureXPText.Text = ("XP %d/%d • Nights %d/%d"):format(record.XP, stage.XPToEvolve, record.StageNights, stage.NightsToEvolve)
		else
			refs.CreatureXPFill.Size = UDim2.fromScale(1, 1)
			refs.CreatureXPText.Text = "MAX STAGE • " .. record.Nights .. " nights survived"
		end
		refs.EvolveButton.Visible = CD.CanEvolve(record)
	end
	refs.Objective.Text = objectiveText(profile)
end

local function refreshCreatureAttributes()
	local hp = player:GetAttribute("CreatureHP") or 0
	local maxHp = player:GetAttribute("CreatureMaxHP") or 1
	local ko = player:GetAttribute("CreatureKO")
	refs.CreatureHPFill.Size = UDim2.fromScale(math.clamp(hp / maxHp, 0, 1), 1)
	refs.CreatureHPFill.BackgroundColor3 = if ko then C.Bad elseif hp / maxHp < 0.35 then Color3.fromRGB(255, 170, 60) else C.Good
	refs.CreatureHPText.Text = if ko then "KNOCKED OUT" else ("%d / %d"):format(hp, maxHp)
	local mode = player:GetAttribute("CreatureMode") or "Attack"
	for name, button in refs.ModeButtons do
		local selected = button:GetAttribute("SelectedColor") or Color3.fromRGB(70, 140, 255)
		button.BackgroundColor3 = if name == mode then selected else modeColors[button]
	end
	if ctx.Profile then
		refs.Objective.Text = objectiveText(ctx.Profile)
	end
end

local function refreshPhase()
	local root = ctx.Root
	local phase = root:GetAttribute("Phase") or "Day"
	local night = root:GetAttribute("Night") or 1
	local modifier = root:GetAttribute("Modifier") or "None"
	local isNight = phase == "Night"
	refs.PhaseTitle.Text = if isNight then ("🌙 NIGHT %d"):format(night) else ("☀️ DAY %d"):format(night)
	refs.PhaseTitle.TextColor3 = if isNight then Color3.fromRGB(200, 185, 255) else Color3.fromRGB(255, 225, 130)
	local top = if isNight then Color3.fromRGB(45, 30, 95) else Color3.fromRGB(70, 120, 170)
	if modifier == "BloodMoon" or modifier == "Nightmare" or modifier == "Apocalypse" then
		top = Color3.fromRGB(110, 20, 20)
	end
	if refs.BannerGradient then
		refs.BannerGradient.Color = ColorSequence.new(top, C.Panel)
	end

	local key = phase .. night
	if key ~= lastPhaseKey then
		local first = lastPhaseKey == ""
		lastPhaseKey = key
		if not first or isNight then
			if isNight then
				local sub = if modifier == "BloodMoon" then "🩸 BLOOD MOON - SURVIVE" else "SURVIVE UNTIL MORNING"
				Hud.BigTitle(("NIGHT %d"):format(night), sub, Color3.fromRGB(190, 170, 255))
			else
				Hud.BigTitle(("DAY %d"):format(night), "PREPARE FOR THE NIGHT", Color3.fromRGB(255, 220, 120))
			end
		end
		if not isNight then
			refs.DeathOverlay.Visible = false
		end
	end
end

local function tick()
	local root = ctx.Root
	local phase = root:GetAttribute("Phase") or "Day"
	local remaining = (root:GetAttribute("PhaseEndsAt") or 0) - serverNow()
	local label = if phase == "Night" then "SURVIVE" else "PREPARE"
	refs.PhaseSub.Text = ("%s • %s"):format(label, UIKit.formatTime(remaining))
	refs.PhaseSub.TextColor3 = if phase == "Day" and remaining < 12 then C.Bad else C.SubText

	local readyAt = player:GetAttribute("AbilityReadyAt") or 0
	local cooldown = readyAt - serverNow()
	local record = equippedRecord(ctx.Profile)
	local ability = record and ctx.CreatureData.Families[record.Family].Ability
	if ability then
		refs.AbilityCooldown.Size = UDim2.fromScale(1, math.clamp(cooldown / ability.Cooldown, 0, 1))
		refs.AbilityButton.Text = if cooldown > 0 then ("%s\n%ds"):format(ability.Name, math.ceil(cooldown)) else ability.Name .. "\n[Q]"
	else
		refs.AbilityCooldown.Size = UDim2.fromScale(1, 0)
		refs.AbilityButton.Text = "ABILITY\n[Q]"
	end
	refs.FeedButton.Text = ("🍓 FEED [F]\nx%d"):format(if ctx.Profile then ctx.Profile.Berries else 0)
	refs.Objective.Text = objectiveText(ctx.Profile)

	local incubator = ctx.Profile and ctx.Profile.Incubator
	refs.Incubator.Visible = incubator ~= nil
	if incubator then
		local egg = ctx.EggData[incubator.EggId]
		local total = math.max(0.1, incubator.EndsAt - incubator.StartedAt)
		local left = incubator.EndsAt - serverNow()
		refs.IncubatorText.Text = ("🥚 %s hatching... %s"):format(if egg then egg.Name else "Egg", UIKit.formatTime(left + 0.99))
		refs.IncubatorFill.Size = UDim2.fromScale(math.clamp(1 - left / total, 0, 1), 1)
	end
end

function Hud.SetDead(dead: boolean)
	refs.DeathOverlay.Visible = dead
end

function Hud.Init(context)
	ctx = context
	bind(ctx.Gui)

	for _, attr in { "Phase", "Night", "Modifier" } do
		ctx.Root:GetAttributeChangedSignal(attr):Connect(refreshPhase)
	end
	for _, attr in { "CreatureHP", "CreatureMaxHP", "CreatureKO", "CreatureMode" } do
		player:GetAttributeChangedSignal(attr):Connect(refreshCreatureAttributes)
	end
	ctx.ProfileChanged:Connect(Hud.RefreshProfile)

	refreshPhase()
	refreshCreatureAttributes()

	local acc = 0
	RunService.RenderStepped:Connect(function(dt)
		acc += dt
		if acc >= 0.1 then
			acc = 0
			tick()
		end
	end)
end

return Hud
]=])
make(n1, "ModuleScript", "Layout", [=[
-- The default look of the HUD and menu window. Only builds instances; no gameplay logic.
-- Hud/Panels find every element BY NAME, so a designer can export this layout to StarterGui,
-- restyle it freely in Studio, and the game will use their version (see README "Editing the UI").
--
-- Responsive rules used everywhere:
--  * Each HUD group is sized relative to SCREEN HEIGHT (SizeConstraint = RelativeYY), so it keeps its
--    shape on phones, tablets, PCs and 4K. Designed at 720p: yy(300, 62) = 300x62 px on a 720px-tall screen.
--  * Everything inside a group uses Scale only, so it grows/shrinks with the group.
--  * Round/square buttons have UIAspectRatioConstraint; groups have UISizeConstraint minimums.
--  * Each group has a UIScale named "AutoScale" (shrinks on narrow screens) and some have a
--    "TouchPosition" attribute (used on phones/tablets to dodge Roblox's thumbstick and jump button).
--  * The ScreenGui respects phone notches (ScreenInsets = DeviceSafeInsets).
local StarterGui = game:GetService("StarterGui")

local UIKit = require(script.Parent.UIKit)

local Layout = {}

Layout.GUI_NAME = "HatchOrDieUI"
local C = UIKit.Colors
local REF = 720

local function named(inst: Instance, name: string)
	inst.Name = name
	return inst
end

local function yy(width: number, height: number): UDim2
	return UDim2.fromScale(width / REF, height / REF)
end

-- Turns a top-level frame into a responsive group.
local function group(frame: GuiObject, minHeight: number?): GuiObject
	frame.SizeConstraint = Enum.SizeConstraint.RelativeYY
	UIKit.new("UIScale", { Name = "AutoScale", Parent = frame })
	if minHeight then
		local ratio = (frame.Size.X.Scale / frame.Size.Y.Scale)
		UIKit.new("UISizeConstraint", { MinSize = Vector2.new(math.floor(minHeight * ratio), minHeight), Parent = frame })
	end
	return frame
end

local function aspect(frame: Instance, ratio: number)
	UIKit.new("UIAspectRatioConstraint", { AspectRatio = ratio, Parent = frame })
end

local function scalePadding(frame: Instance, amount: number)
	UIKit.new("UIPadding", {
		PaddingTop = UDim.new(amount, 0),
		PaddingBottom = UDim.new(amount, 0),
		PaddingLeft = UDim.new(amount * 0.6, 0),
		PaddingRight = UDim.new(amount * 0.6, 0),
		Parent = frame,
	})
end

local function bar(parent: Instance, name: string, position: UDim2, size: UDim2, color: Color3)
	local back, fill = UIKit.bar({ Position = position, Size = size, Parent = parent }, color)
	back.Name = name .. "Back"
	fill.Name = name
	return back, fill
end

local function text(props)
	props.Size = props.Size or UDim2.fromScale(1, 1)
	return UIKit.text(props)
end

function Layout.BuildHud(gui: ScreenGui)
	-- Phase banner (top center)
	local banner = group(UIKit.panel({ Name = "PhaseBanner", AnchorPoint = Vector2.new(0.5, 0), Position = UDim2.fromScale(0.5, 0.01), Size = yy(300, 62), Parent = gui }))
	UIKit.new("UIGradient", { Rotation = 90, Color = ColorSequence.new(Color3.fromRGB(70, 120, 170), C.Panel), Parent = banner })
	named(text({ Position = UDim2.fromScale(0.03, 0.06), Size = UDim2.fromScale(0.94, 0.55), Font = Enum.Font.FredokaOne, TextStrokeTransparency = 0.3, Text = "☀️ DAY 1", TextColor3 = Color3.fromRGB(255, 225, 130), Parent = banner }), "PhaseTitle")
	named(text({ Position = UDim2.fromScale(0.03, 0.62), Size = UDim2.fromScale(0.94, 0.3), TextColor3 = C.SubText, Text = "PREPARE • 0:40", Parent = banner }), "PhaseSub")

	local objective = group(named(text({
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.fromScale(0.5, 0.105),
		Size = yy(440, 24),
		BackgroundTransparency = 0.45,
		BackgroundColor3 = C.Bg,
		Font = Enum.Font.GothamMedium,
		Text = "🥚 Your first egg is hatching... get ready!",
		Parent = gui,
	}), "Objective"))
	UIKit.corner(objective, 8)

	-- Boss bar (under the objective)
	local boss = group(UIKit.new("Frame", { Name = "BossBar", AnchorPoint = Vector2.new(0.5, 0), Position = UDim2.fromScale(0.5, 0.15), Size = yy(440, 42), BackgroundTransparency = 1, Parent = gui }))
	named(text({ Size = UDim2.fromScale(1, 0.44), Font = Enum.Font.FredokaOne, TextColor3 = Color3.fromRGB(255, 120, 90), TextStrokeTransparency = 0.2, Text = "Rotwood Colossus", Parent = boss }), "BossName")
	local bossBack = bar(boss, "BossFill", UDim2.fromScale(0, 0.5), UDim2.fromScale(1, 0.45), Color3.fromRGB(220, 50, 50))
	UIKit.stroke(bossBack, Color3.new(0, 0, 0), 2, 0.2)

	-- Currencies (top left)
	local currencies = group(UIKit.panel({ Name = "Currencies", Position = UDim2.fromScale(0.008, 0.012), Size = yy(150, 92), Parent = gui }), 60)
	scalePadding(currencies, 0.06)
	UIKit.new("UIListLayout", { Padding = UDim.new(0.03, 0), SortOrder = Enum.SortOrder.LayoutOrder, Parent = currencies })
	for i, row in { { "Coins", "🪙 0", C.Gold }, { "Berries", "🍓 0", C.Berry }, { "Best", "🏆 Best: Night 0", C.Text } } do
		named(text({ LayoutOrder = i, Size = UDim2.fromScale(1, 0.31), TextXAlignment = Enum.TextXAlignment.Left, TextColor3 = row[3], Font = Enum.Font.FredokaOne, Text = row[2], Parent = currencies }), row[1])
	end

	-- Creature card (left middle)
	local card = group(UIKit.panel({ Name = "CreatureCard", AnchorPoint = Vector2.new(0, 0.5), Position = UDim2.fromScale(0.008, 0.45), Size = yy(230, 128), Parent = gui }), 84)
	scalePadding(card, 0.06)
	named(text({ Size = UDim2.fromScale(1, 0.2), Font = Enum.Font.FredokaOne, TextXAlignment = Enum.TextXAlignment.Left, Text = "🌿 Sproutling", Parent = card }), "CreatureName")
	named(text({ Position = UDim2.fromScale(0, 0.21), Size = UDim2.fromScale(1, 0.13), TextColor3 = C.SubText, TextXAlignment = Enum.TextXAlignment.Left, Text = "Common • Baby • Stage 1/3", Parent = card }), "CreatureStage")
	bar(card, "CreatureHPFill", UDim2.fromScale(0, 0.37), UDim2.fromScale(1, 0.13), C.Good)
	named(text({ Position = UDim2.fromScale(0, 0.37), Size = UDim2.fromScale(1, 0.13), TextStrokeTransparency = 0.2, Text = "140 / 140", Parent = card }), "CreatureHPText")
	bar(card, "CreatureXPFill", UDim2.fromScale(0, 0.53), UDim2.fromScale(1, 0.08), C.Accent)
	named(text({ Position = UDim2.fromScale(0, 0.63), Size = UDim2.fromScale(1, 0.12), TextColor3 = C.SubText, TextXAlignment = Enum.TextXAlignment.Left, Text = "XP 0/100 • Nights 0/1", Parent = card }), "CreatureXPText")
	UIKit.button({ Name = "EvolveButton", Position = UDim2.fromScale(0, 0.79), Size = UDim2.fromScale(1, 0.21), BackgroundColor3 = C.Gold, TextColor3 = Color3.fromRGB(40, 25, 0), Text = "✨ EVOLVE!", Parent = card })

	-- Actions: commands, feed, ability (bottom right; moves up on touch devices)
	local actions = group(UIKit.new("Frame", { Name = "Actions", AnchorPoint = Vector2.new(1, 1), Position = UDim2.fromScale(0.992, 0.985), Size = yy(250, 170), BackgroundTransparency = 1, Parent = gui }))
	actions:SetAttribute("TouchPosition", UDim2.fromScale(0.992, 0.64))
	for i, mode in { "Follow", "Attack", "Defend" } do
		UIKit.button({ Name = "Mode" .. mode, Position = UDim2.fromScale((i - 1) / 3 + 0.005, 0), Size = UDim2.fromScale(0.323, 0.2), Text = ("%s [%d]"):format(mode, i), Parent = actions })
	end
	local feed = UIKit.button({ Name = "FeedButton", AnchorPoint = Vector2.new(0, 1), Position = UDim2.fromScale(0.06, 1), Size = UDim2.fromScale(0.38, 0.56), BackgroundColor3 = Color3.fromRGB(150, 50, 80), Text = "🍓 FEED [F]\nx0", Parent = actions })
	aspect(feed, 1)
	local ability = UIKit.button({ Name = "AbilityButton", AnchorPoint = Vector2.new(1, 1), Position = UDim2.fromScale(1, 1), Size = UDim2.fromScale(0.48, 0.72), BackgroundColor3 = Color3.fromRGB(80, 60, 170), Text = "ABILITY\n[Q]", Parent = actions })
	aspect(ability, 1)
	ability:FindFirstChildOfClass("UICorner").CornerRadius = UDim.new(1, 0)
	local cooldown = UIKit.new("Frame", { Name = "AbilityCooldown", Size = UDim2.fromScale(1, 0), AnchorPoint = Vector2.new(0, 1), Position = UDim2.fromScale(0, 1), BackgroundColor3 = Color3.new(0, 0, 0), BackgroundTransparency = 0.45, BorderSizePixel = 0, ZIndex = 2, Parent = ability })
	UIKit.new("UICorner", { CornerRadius = UDim.new(1, 0), Parent = cooldown })

	-- Menu bar (bottom center)
	local menu = group(UIKit.new("Frame", { Name = "Menu", AnchorPoint = Vector2.new(0.5, 1), Position = UDim2.fromScale(0.5, 0.985), Size = yy(330, 58), BackgroundTransparency = 1, Parent = gui }))
	UIKit.new("UIListLayout", { FillDirection = Enum.FillDirection.Horizontal, HorizontalAlignment = Enum.HorizontalAlignment.Center, Padding = UDim.new(0.025, 0), SortOrder = Enum.SortOrder.LayoutOrder, Parent = menu })
	for i, item in { { "Eggs", "🥚 Eggs" }, { "Creatures", "🐲 Creatures" }, { "Shop", "🛒 Shop" } } do
		UIKit.button({ Name = "Menu" .. item[1], LayoutOrder = i, Size = UDim2.fromScale(0.31, 0.93), BackgroundColor3 = C.Panel, Text = item[2], Parent = menu })
	end
	local badge = named(text({ AnchorPoint = Vector2.new(0.5, 0.5), Position = UDim2.fromScale(0.95, 0.05), Size = UDim2.fromScale(0.45, 0.45), BackgroundTransparency = 0, BackgroundColor3 = C.Bad, Font = Enum.Font.FredokaOne, Text = "1", ZIndex = 3, Parent = menu:FindFirstChild("MenuEggs") }), "EggBadge")
	aspect(badge, 1)
	UIKit.new("UICorner", { CornerRadius = UDim.new(1, 0), Parent = badge })

	-- Incubator timer (above the menu)
	local incubator = group(UIKit.panel({ Name = "Incubator", AnchorPoint = Vector2.new(0.5, 1), Position = UDim2.fromScale(0.5, 0.89), Size = yy(300, 46), Parent = gui }))
	named(text({ Position = UDim2.fromScale(0.03, 0.08), Size = UDim2.fromScale(0.94, 0.46), Font = Enum.Font.FredokaOne, Text = "🥚 Forest Egg hatching... 0:10", Parent = incubator }), "IncubatorText")
	bar(incubator, "IncubatorFill", UDim2.fromScale(0.03, 0.62), UDim2.fromScale(0.94, 0.22), C.Gold)

	-- Notifications (top right)
	local toasts = group(UIKit.new("Frame", { Name = "Toasts", AnchorPoint = Vector2.new(1, 0), Position = UDim2.fromScale(0.992, 0.012), Size = yy(320, 190), BackgroundTransparency = 1, Parent = gui }))
	UIKit.new("UIListLayout", { Padding = UDim.new(0.02, 0), HorizontalAlignment = Enum.HorizontalAlignment.Right, SortOrder = Enum.SortOrder.LayoutOrder, Parent = toasts })

	-- Center messages (relative to the whole screen)
	named(text({ AnchorPoint = Vector2.new(0.5, 0), Position = UDim2.fromScale(0.5, 0.21), Size = UDim2.fromScale(0.8, 0.055), Font = Enum.Font.FredokaOne, TextStrokeTransparency = 0.1, TextColor3 = C.Gold, Text = "🌟 PLAYER HATCHED A CELESTIAL DRAGON!", Parent = gui }), "Announcement")
	named(text({ AnchorPoint = Vector2.new(0.5, 0.5), Position = UDim2.fromScale(0.5, 0.36), Size = UDim2.fromScale(0.8, 0.125), Font = Enum.Font.FredokaOne, TextStrokeTransparency = 0, TextStrokeColor3 = Color3.new(0, 0, 0), Text = "NIGHT 1", TextColor3 = Color3.fromRGB(190, 170, 255), Parent = gui }), "BigTitle")
	named(text({ AnchorPoint = Vector2.new(0.5, 0.5), Position = UDim2.fromScale(0.5, 0.445), Size = UDim2.fromScale(0.6, 0.045), Font = Enum.Font.FredokaOne, TextStrokeTransparency = 0.2, Text = "SURVIVE UNTIL MORNING", Parent = gui }), "BigSub")

	local result = group(UIKit.panel({ Name = "NightResult", AnchorPoint = Vector2.new(0.5, 0.5), Position = UDim2.fromScale(0.5, 0.56), Size = yy(360, 190), Parent = gui }), 130)
	scalePadding(result, 0.06)
	named(text({ Size = UDim2.fromScale(1, 0.22), Font = Enum.Font.FredokaOne, TextColor3 = C.Gold, Text = "☀️ NIGHT 1 SURVIVED!", Parent = result }), "ResultTitle")
	local body = named(text({ Position = UDim2.fromScale(0, 0.27), Size = UDim2.fromScale(1, 0.73), TextYAlignment = Enum.TextYAlignment.Top, Font = Enum.Font.GothamBold, Text = "🪙 +37 coins\n✨ +55 creature XP\n🍓 +2 berries", Parent = result }), "ResultBody")
	UIKit.new("UITextSizeConstraint", { MaxTextSize = 30, Parent = body })

	local death = named(text({ Size = UDim2.fromScale(1, 1), BackgroundColor3 = Color3.fromRGB(80, 0, 0), BackgroundTransparency = 0.55, Text = "💀 YOU FELL\nYou'll return at dawn... if anyone survives.", Font = Enum.Font.FredokaOne, ZIndex = 0, Parent = gui }), "DeathOverlay")
	UIKit.new("UITextSizeConstraint", { MaxTextSize = 48, Parent = death })
end

function Layout.BuildWindow(gui: ScreenGui)
	local window = UIKit.panel({ Name = "Window", AnchorPoint = Vector2.new(0.5, 0.5), Position = UDim2.fromScale(0.5, 0.5), Size = UDim2.fromScale(0.9, 0.8), BackgroundColor3 = C.Bg, BackgroundTransparency = 0.05, ZIndex = 5, Parent = gui })
	UIKit.new("UISizeConstraint", { MaxSize = Vector2.new(1100, 720), Parent = window })
	scalePadding(window, 0.025)
	named(text({ Size = UDim2.fromScale(0.85, 0.08), Font = Enum.Font.FredokaOne, TextXAlignment = Enum.TextXAlignment.Left, Text = "🥚 EGGS", Parent = window }), "WindowTitle")
	local close = UIKit.button({ Name = "WindowClose", AnchorPoint = Vector2.new(1, 0), Position = UDim2.fromScale(1, 0), Size = UDim2.fromScale(0.1, 0.08), BackgroundColor3 = C.Bad, Text = "X", Parent = window })
	aspect(close, 1.25)
	UIKit.new("Frame", { Name = "WindowContent", Position = UDim2.fromScale(0, 0.1), Size = UDim2.fromScale(1, 0.9), BackgroundTransparency = 1, Parent = window })
end

-- Builds a complete default ScreenGui (used for the in-game default and for the StarterGui export).
function Layout.Build(): ScreenGui
	local gui = UIKit.new("ScreenGui", {
		Name = Layout.GUI_NAME,
		ResetOnSpawn = false,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
		ScreenInsets = Enum.ScreenInsets.DeviceSafeInsets,
	})
	Layout.BuildHud(gui)
	Layout.BuildWindow(gui)
	return gui
end

-- Uses the designer's StarterGui.HatchOrDieUI when present, otherwise the built-in layout.
function Layout.Obtain(player: Player): ScreenGui
	local playerGui = player:WaitForChild("PlayerGui")
	local template = StarterGui:FindFirstChild(Layout.GUI_NAME)
	local gui
	if template then
		gui = playerGui:WaitForChild(Layout.GUI_NAME, 10)
		if not gui then
			gui = template:Clone()
		end
	else
		gui = Layout.Build()
	end
	gui.ResetOnSpawn = false
	gui.Parent = playerGui
	return gui
end

-- Finds a UI element by name anywhere in the gui. Missing elements are replaced by hidden
-- placeholders so a designer deleting something never breaks the game.
function Layout.Finder(gui: ScreenGui)
	local missing = UIKit.new("Frame", { Name = "MissingElements", Visible = false, Parent = gui })
	return function(name: string, className: string?): any
		local found = gui:FindFirstChild(name, true)
		if found then
			return found
		end
		warn(("[HatchOrDie UI] '%s' not found in %s - add an element with that name to show it."):format(name, gui.Name))
		return UIKit.new(className or "TextButton", { Name = name, Parent = missing })
	end
end

-- Runtime responsiveness: shrink groups on narrow screens and move TouchPosition groups on phones.
function Layout.MakeResponsive(gui: ScreenGui)
	local UserInputService = game:GetService("UserInputService")
	local isTouch = UserInputService.TouchEnabled and not UserInputService.KeyboardEnabled
	local scales = {}
	for _, d in gui:GetDescendants() do
		if d:IsA("UIScale") and d.Name == "AutoScale" then
			table.insert(scales, d)
		elseif isTouch and d:IsA("GuiObject") then
			local touchPosition = d:GetAttribute("TouchPosition")
			if typeof(touchPosition) == "UDim2" then
				d.Position = touchPosition
			end
		end
	end
	local function fit()
		local camera = workspace.CurrentCamera
		if not camera then
			return
		end
		local viewport = camera.ViewportSize
		local ratio = viewport.X / math.max(viewport.Y, 1)
		-- 16:9 and wider = 1. 4:3 tablets ~0.83. Portrait screens bottom out at 0.45.
		local scale = math.clamp(ratio / 1.6, 0.45, 1)
		for _, s in scales do
			s.Scale = scale
		end
	end
	fit()
	local camera = workspace.CurrentCamera
	if camera then
		camera:GetPropertyChangedSignal("ViewportSize"):Connect(fit)
	end
end

return Layout
]=])
make(n1, "ModuleScript", "Panels", [=[
-- Modal menus: Eggs (with odds), Creatures (collection + evolve/equip/aura), Shop.
local Players = game:GetService("Players")
local MarketplaceService = game:GetService("MarketplaceService")

local UIKit = require(script.Parent.UIKit)

local Panels = {}

local player = Players.LocalPlayer
local C = UIKit.Colors

local ctx
local window: Frame
local titleLabel: TextLabel
local content: Frame
local windowSize: UDim2
local current: string? = nil
local selectedCreature: string? = nil
local shopTab = "Eggs"
local lastSignature = ""

local function clear()
	for _, child in content:GetChildren() do
		child:Destroy()
	end
end

local function scrolling(props): ScrollingFrame
	local defaults = {
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ScrollBarThickness = 6,
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		CanvasSize = UDim2.new(),
		ScrollingDirection = Enum.ScrollingDirection.Y,
	}
	for k, v in props do
		defaults[k] = v
	end
	return UIKit.new("ScrollingFrame", defaults)
end

-- Menus are sized from the window's real pixel size so cards fit phones, tablets and PCs.
local function contentSize(): Vector2
	local abs = content.AbsoluteSize
	if abs and abs.X > 50 and abs.Y > 50 then
		return abs
	end
	local camera = workspace.CurrentCamera
	local viewport = if camera then camera.ViewportSize else Vector2.new(1280, 720)
	return Vector2.new(math.min(viewport.X * 0.85, 1050), math.min(viewport.Y * 0.68, 620))
end

-- Grid whose columns adapt to the available width. heightRatio = cell height / cell width.
local function grid(list: Instance, width: number, minCellWidth: number, heightRatio: number, sortOrder: Enum.SortOrder?)
	local pad = math.max(4, math.floor(width * 0.012))
	local columns = math.max(1, math.floor((width + pad) / (minCellWidth + pad)))
	local cellWidth = math.floor((width - 10 - pad * (columns - 1)) / columns)
	return UIKit.new("UIGridLayout", {
		CellSize = UDim2.fromOffset(cellWidth, math.floor(cellWidth * heightRatio)),
		CellPadding = UDim2.fromOffset(pad, pad),
		SortOrder = sortOrder or Enum.SortOrder.LayoutOrder,
		Parent = list,
	})
end

local function oddsText(egg): string
	local total = 0
	for _, entry in egg.Pool do
		total += entry.Weight
	end
	local parts = {}
	for _, entry in egg.Pool do
		table.insert(parts, ("%s %s %.0f%%"):format(UIKit.FamilyIcons[entry.Family], entry.Family, entry.Weight / total * 100))
	end
	return table.concat(parts, "  ") .. ("\n🧬 Mutation chance %.0f%%"):format(egg.MutationChance * 100)
end

local function sortedEggIds(): { string }
	local ids = {}
	for id in ctx.EggData do
		table.insert(ids, id)
	end
	table.sort(ids, function(a, b)
		return ctx.EggData[a].Order < ctx.EggData[b].Order
	end)
	return ids
end

---------------------------------------------------------------------------------------------------
-- Eggs
---------------------------------------------------------------------------------------------------
local function renderEggs()
	local profile = ctx.Profile
	titleLabel.Text = ("🥚 EGGS (%d/%d)"):format(#profile.Eggs, ctx.GameConfig.MaxEggs)

	local size = contentSize()
	local status = UIKit.text({ Size = UDim2.fromScale(1, 0.07), TextColor3 = C.SubText, Parent = content })
	if profile.Incubator then
		local egg = ctx.EggData[profile.Incubator.EggId]
		status.Text = ("Incubating: %s - watch the timer above the menu"):format(if egg then egg.Name else "Egg")
		status.TextColor3 = C.Gold
	else
		status.Text = "Your incubator is empty - pick an egg to hatch!"
	end

	local list = scrolling({ Position = UDim2.fromScale(0, 0.08), Size = UDim2.fromScale(1, 0.92), Parent = content })
	grid(list, size.X, 170, 1.3)

	local counts = {}
	local firstOf = {}
	for _, egg in profile.Eggs do
		counts[egg.EggId] = (counts[egg.EggId] or 0) + 1
		firstOf[egg.EggId] = firstOf[egg.EggId] or egg.Id
	end

	for _, eggId in sortedEggIds() do
		local egg = ctx.EggData[eggId]
		local count = counts[eggId] or 0
		local card = UIKit.panel({ BackgroundColor3 = C.PanelLight, Parent = list })
		UIKit.padding(card, 8)
		UIKit.viewport({ Size = UDim2.fromScale(1, 0.3), Parent = card }, ctx.Models.BuildEgg(eggId), true)
		UIKit.text({ Position = UDim2.fromScale(0, 0.31), Size = UDim2.fromScale(1, 0.1), Text = egg.Name, Font = Enum.Font.FredokaOne, TextColor3 = ctx.Rarity.Colors[egg.Rarity], Parent = card })
		UIKit.text({ Position = UDim2.fromScale(0, 0.42), Size = UDim2.fromScale(1, 0.07), Text = ("%s • %ds • Owned x%d"):format(egg.Rarity, egg.HatchTime, count), TextColor3 = C.SubText, Parent = card })
		UIKit.text({ Position = UDim2.fromScale(0, 0.51), Size = UDim2.fromScale(1, 0.28), Text = oddsText(egg), TextColor3 = C.Text, Font = Enum.Font.Gotham, Parent = card })
		if count > 0 then
			UIKit.button({
				Position = UDim2.fromScale(0, 0.82),
				Size = UDim2.fromScale(1, 0.18),
				BackgroundColor3 = if profile.Incubator then C.PanelLight else Color3.fromRGB(70, 170, 90),
				Text = if profile.Incubator then "Incubator busy" else "HATCH",
				Parent = card,
			}, function()
				ctx.Net.Get("RequestHatch"):FireServer(firstOf[eggId])
			end)
		else
			UIKit.button({
				Position = UDim2.fromScale(0, 0.82),
				Size = UDim2.fromScale(1, 0.18),
				Text = ("Buy - 🪙 %d"):format(egg.Price),
				Parent = card,
			}, function()
				ctx.Net.Get("BuyItem"):FireServer(eggId)
			end)
		end
	end
end

---------------------------------------------------------------------------------------------------
-- Creatures
---------------------------------------------------------------------------------------------------
local function findCreature(id: string?)
	if not id then
		return nil
	end
	for _, record in ctx.Profile.Creatures do
		if record.Id == id then
			return record
		end
	end
	return nil
end

local function totalDiscoverable(): number
	local CD = ctx.CreatureData
	local families = 0
	for _ in CD.Families do
		families += 1
	end
	return families * #CD.Stages * (1 + #CD.Mutations)
end

local function renderCreatureDetail(parent: Frame, record)
	local CD = ctx.CreatureData
	local profile = ctx.Profile
	local rarity = CD.GetRarity(record)
	local stats = CD.GetStats(record)
	local family = CD.Families[record.Family]
	local stage = CD.Stages[record.Stage]

	UIKit.viewport({ Size = UDim2.fromScale(1, 0.4), Parent = parent }, ctx.Models.BuildCreature(record), true)
	UIKit.text({ Position = UDim2.fromScale(0, 0.41), Size = UDim2.fromScale(1, 0.075), Text = CD.GetDisplayName(record), Font = Enum.Font.FredokaOne, TextColor3 = ctx.Rarity.Colors[rarity], Parent = parent })
	UIKit.text({
		Position = UDim2.fromScale(0, 0.49),
		Size = UDim2.fromScale(1, 0.045),
		Text = ("%s • %s • %s"):format(rarity, stage.Name, if record.Mutation then "🧬 " .. record.Mutation else "No mutation"),
		TextColor3 = C.SubText,
		Parent = parent,
	})
	UIKit.text({
		Position = UDim2.fromScale(0, 0.54),
		Size = UDim2.fromScale(1, 0.09),
		Text = ("❤️ %d  ⚔️ %.1f  🎯 %.0f\n✨ %s"):format(stats.MaxHealth, stats.Damage, stats.Range, family.Ability.Name),
		Font = Enum.Font.Gotham,
		Parent = parent,
	})

	local nextText
	if stage.XPToEvolve then
		local nextRecord = table.clone(record)
		nextRecord.Stage += 1
		nextRecord.Mutation = nil
		local known = profile.Discovered[CD.DiscoveryKey(nextRecord)]
		local nextName = if known then CD.GetStageName(nextRecord) else "???"
		nextText = ("Next: %s  |  XP %d/%d  |  Nights %d/%d"):format(nextName, record.XP, stage.XPToEvolve, record.StageNights, stage.NightsToEvolve)
	else
		nextText = ("Fully evolved • %d nights survived"):format(record.Nights)
	end
	UIKit.text({ Position = UDim2.fromScale(0, 0.64), Size = UDim2.fromScale(1, 0.045), Text = nextText, TextColor3 = C.Accent, Parent = parent })

	local buttons = UIKit.new("Frame", { Position = UDim2.fromScale(0, 0.7), Size = UDim2.fromScale(1, 0.1), BackgroundTransparency = 1, Parent = parent })
	UIKit.new("UIListLayout", { FillDirection = Enum.FillDirection.Horizontal, Padding = UDim.new(0, 4), Parent = buttons })
	local equipped = profile.Equipped == record.Id
	UIKit.button({ Size = UDim2.new(0.25, -3, 1, 0), BackgroundColor3 = if equipped then C.PanelLight else Color3.fromRGB(70, 140, 255), Text = if equipped then "Equipped" else "Equip", Parent = buttons }, function()
		ctx.Net.Get("EquipCreature"):FireServer(record.Id)
	end)
	local canEvolve = CD.CanEvolve(record)
	UIKit.button({ Size = UDim2.new(0.25, -3, 1, 0), BackgroundColor3 = if canEvolve then C.Gold else C.PanelLight, TextColor3 = if canEvolve then Color3.fromRGB(40, 25, 0) else C.SubText, Text = "Evolve", Parent = buttons }, function()
		ctx.Net.Get("EvolveCreature"):FireServer(record.Id)
	end)
	UIKit.button({ Size = UDim2.new(0.25, -3, 1, 0), Text = if record.Locked then "🔒 Locked" else "🔓 Lock", Parent = buttons }, function()
		ctx.Net.Get("ToggleLock"):FireServer(record.Id)
	end)
	UIKit.button({ Size = UDim2.new(0.25, -3, 1, 0), BackgroundColor3 = Color3.fromRGB(150, 50, 50), Text = "Release", Parent = buttons }, function()
		ctx.Net.Get("ReleaseCreature"):FireServer(record.Id)
	end)

	if equipped then
		local auras = UIKit.new("Frame", { Position = UDim2.fromScale(0, 0.82), Size = UDim2.fromScale(1, 0.18), BackgroundTransparency = 1, Parent = parent })
		UIKit.new("UIGridLayout", { CellSize = UDim2.fromScale(0.235, 0.45), CellPadding = UDim2.fromScale(0.02, 0.08), Parent = auras })
		UIKit.button({ Text = "No aura", Parent = auras }, function()
			ctx.Net.Get("EquipAura"):FireServer("")
		end)
		for auraId, aura in ctx.CreatureData.Auras do
			local owned = profile.Auras[auraId] or (auraId == "Golden" and player:GetAttribute("Pass_VIP"))
			if owned then
				UIKit.button({ BackgroundColor3 = aura.Color:Lerp(Color3.new(0, 0, 0), 0.4), Text = aura.Name:gsub(" Aura", ""), Parent = auras }, function()
					ctx.Net.Get("EquipAura"):FireServer(auraId)
				end)
			end
		end
	end
end

local function renderCreatures()
	local profile = ctx.Profile
	local CD = ctx.CreatureData
	local discovered = 0
	for _ in profile.Discovered do
		discovered += 1
	end
	titleLabel.Text = ("🐲 CREATURES (%d/%d) • Discovered %d/%d"):format(#profile.Creatures, ctx.SlotLimit(), discovered, totalDiscoverable())

	if #profile.Creatures == 0 then
		UIKit.text({ Size = UDim2.fromScale(1, 0.1), Text = "No creatures yet - hatch an egg!", Parent = content })
		return
	end
	if not findCreature(selectedCreature) then
		selectedCreature = profile.Equipped or profile.Creatures[1].Id
	end

	local list = scrolling({ Size = UDim2.new(0.5, -6, 1, 0), Parent = content })
	grid(list, contentSize().X * 0.5 - 6, 95, 0.75)

	local sorted = table.clone(profile.Creatures)
	table.sort(sorted, function(a, b)
		if (a.Id == profile.Equipped) ~= (b.Id == profile.Equipped) then
			return a.Id == profile.Equipped
		end
		local ra, rb = ctx.Rarity.Rank[CD.GetRarity(a)], ctx.Rarity.Rank[CD.GetRarity(b)]
		if ra ~= rb then
			return ra > rb
		end
		return a.Stage > b.Stage
	end)

	for i, record in sorted do
		local rarity = CD.GetRarity(record)
		local selected = record.Id == selectedCreature
		local card = UIKit.button({
			LayoutOrder = i,
			BackgroundColor3 = if selected then ctx.Rarity.Colors[rarity]:Lerp(C.Panel, 0.55) else C.PanelLight,
			Text = "",
			Parent = list,
		}, function()
			selectedCreature = record.Id
			Panels.Render(true)
		end)
		card:FindFirstChildOfClass("UIStroke").Color = ctx.Rarity.Colors[rarity]
		UIKit.text({ Size = UDim2.fromScale(1, 0.4), Text = UIKit.FamilyIcons[record.Family] .. (if record.Mutation then "🧬" else ""), Parent = card })
		UIKit.text({ Position = UDim2.fromScale(0.03, 0.4), Size = UDim2.fromScale(0.94, 0.32), Text = CD.GetDisplayName(record), TextColor3 = ctx.Rarity.Colors[rarity], Parent = card })
		local tags = (if record.Id == profile.Equipped then "⭐ " else "") .. (if record.Locked then "🔒 " else "") .. CD.Stages[record.Stage].Name
		UIKit.text({ Position = UDim2.fromScale(0.03, 0.72), Size = UDim2.fromScale(0.94, 0.22), Text = tags, TextColor3 = C.SubText, Parent = card })
	end

	local detail = UIKit.new("Frame", { Position = UDim2.new(0.5, 6, 0, 0), Size = UDim2.new(0.5, -6, 1, 0), BackgroundTransparency = 1, Parent = content })
	local record = findCreature(selectedCreature)
	if record then
		renderCreatureDetail(detail, record)
	end
end

---------------------------------------------------------------------------------------------------
-- Shop
---------------------------------------------------------------------------------------------------
local function shopRow(parent: Instance, name: string, description: string, priceText: string, buttonText: string, enabled: boolean, onBuy: () -> ())
	local rowHeight = math.clamp(math.floor(contentSize().Y * 0.16), 48, 110)
	local row = UIKit.panel({ Size = UDim2.new(1, -8, 0, rowHeight), BackgroundColor3 = C.PanelLight, Parent = parent })
	UIKit.text({ Position = UDim2.fromScale(0.02, 0.08), Size = UDim2.fromScale(0.6, 0.38), Text = name, Font = Enum.Font.FredokaOne, TextXAlignment = Enum.TextXAlignment.Left, Parent = row })
	UIKit.text({ Position = UDim2.fromScale(0.02, 0.5), Size = UDim2.fromScale(0.6, 0.42), Text = description, TextColor3 = C.SubText, Font = Enum.Font.Gotham, TextXAlignment = Enum.TextXAlignment.Left, Parent = row })
	UIKit.button({
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -10, 0.5, 0),
		Size = UDim2.fromScale(0.34, 0.7),
		BackgroundColor3 = if enabled then Color3.fromRGB(70, 170, 90) else C.Panel,
		TextColor3 = if enabled then C.Text else C.SubText,
		Text = if buttonText ~= "" then buttonText else priceText,
		Parent = row,
	}, function()
		if enabled then
			onBuy()
		end
	end)
end

local function renderShop()
	local profile = ctx.Profile
	titleLabel.Text = ("🛒 SHOP • 🪙 %s"):format(UIKit.formatNumber(profile.Coins))

	local tabs = UIKit.new("Frame", { Size = UDim2.fromScale(1, 0.085), BackgroundTransparency = 1, Parent = content })
	UIKit.new("UIListLayout", { FillDirection = Enum.FillDirection.Horizontal, Padding = UDim.new(0, 6), Parent = tabs })
	for _, category in ctx.ShopData.Categories do
		UIKit.button({
			Size = UDim2.new(0.25, -5, 1, 0),
			BackgroundColor3 = if category == shopTab then Color3.fromRGB(70, 140, 255) else C.PanelLight,
			Text = category,
			Parent = tabs,
		}, function()
			shopTab = category
			Panels.Render(true)
		end)
	end

	local list = scrolling({ Position = UDim2.fromScale(0, 0.1), Size = UDim2.fromScale(1, 0.9), Parent = content })
	UIKit.new("UIListLayout", { Padding = UDim.new(0, 6), Parent = list })

	if shopTab == "Robux" then
		for _, item in ctx.ShopData.Robux do
			local configTable = if item.Kind == "Gamepass" then ctx.GameConfig.Gamepasses else ctx.GameConfig.Products
			local id = configTable[item.ConfigKey] or 0
			local owned = item.Kind == "Gamepass" and player:GetAttribute("Pass_" .. item.ConfigKey)
			local buttonText = if owned then "Owned" elseif id == 0 then "Coming soon" else ""
			shopRow(list, item.Name, item.Description, ("R$ %d"):format(item.Robux), buttonText, id ~= 0 and not owned, function()
				if item.Kind == "Gamepass" then
					MarketplaceService:PromptGamePassPurchase(player, id)
				else
					MarketplaceService:PromptProductPurchase(player, id)
				end
			end)
		end
		UIKit.text({ Size = UDim2.new(1, -8, 0, math.clamp(math.floor(contentSize().Y * 0.09), 24, 60)), Text = "Robux items are convenience & cosmetics only. Everything that matters in a fight can be earned by playing.", TextColor3 = C.SubText, Font = Enum.Font.Gotham, Parent = list })
		return
	end

	for _, item in ctx.ShopData.Items do
		if item.Category == shopTab then
			local description = item.Description or ""
			local owned = false
			if item.Kind == "Egg" then
				description = oddsText(ctx.EggData[item.EggId]):gsub("\n", "  ")
			elseif item.Kind == "Aura" then
				owned = profile.Auras[item.AuraId] == true
				description = "Cosmetic only - particles + glow on your creature."
			end
			local affordable = profile.Coins >= item.Price
			local buttonText = if owned then "Owned" else ""
			shopRow(list, item.Name, description, ("🪙 %d"):format(item.Price), buttonText, affordable and not owned, function()
				ctx.Net.Get("BuyItem"):FireServer(item.Id)
			end)
		end
	end
end

---------------------------------------------------------------------------------------------------
-- Window
---------------------------------------------------------------------------------------------------
local RENDERERS = { Eggs = renderEggs, Creatures = renderCreatures, Shop = renderShop }

local function signature(): string
	local profile = ctx.Profile
	if not profile then
		return ""
	end
	local coins = if current == "Shop" then tostring(profile.Coins) else ""
	local parts = { current or "", coins, tostring(profile.Equipped), tostring(profile.Incubator ~= nil), tostring(#profile.Eggs) }
	for _, record in profile.Creatures do
		table.insert(parts, ("%s%d%s%s%s%d%d"):format(record.Id, record.Stage, tostring(record.Mutation), tostring(record.Locked), tostring(record.Aura), record.XP, record.StageNights))
	end
	for auraId in profile.Auras do
		table.insert(parts, auraId)
	end
	return table.concat(parts, "|")
end

function Panels.Render(force: boolean?)
	if not current or not ctx.Profile then
		return
	end
	local sig = signature()
	if not force and sig == lastSignature then
		return
	end
	lastSignature = sig
	clear()
	RENDERERS[current]()
end

function Panels.Open(name: string)
	if not RENDERERS[name] then
		return
	end
	current = name
	window.Visible = true
	window.Size = UIKit.scaleUDim2(windowSize, 0.94)
	UIKit.tween(window, 0.2, { Size = windowSize }, Enum.EasingStyle.Back)
	Panels.Render(true)
end

function Panels.Close()
	current = nil
	window.Visible = false
	clear()
end

function Panels.Toggle(name: string)
	if current == name then
		Panels.Close()
	else
		Panels.Open(name)
	end
end

function Panels.IsOpen(): boolean
	return current ~= nil
end

function Panels.Init(context)
	ctx = context
	local find = ctx.Layout.Finder(ctx.Gui)
	window = find("Window", "Frame")
	titleLabel = find("WindowTitle", "TextLabel")
	content = find("WindowContent", "Frame")
	local closeButton = find("WindowClose")
	UIKit.decorate(closeButton)
	closeButton.Activated:Connect(Panels.Close)
	windowSize = window.Size
	window.Visible = false
	local lastWidth = 0
	content:GetPropertyChangedSignal("AbsoluteSize"):Connect(function()
		local width = content.AbsoluteSize.X
		if current and math.abs(width - lastWidth) > 40 then
			lastWidth = width
			Panels.Render(true)
		end
	end)

	ctx.ProfileChanged:Connect(function()
		Panels.Render(false)
	end)
end

return Panels
]=])
make(n1, "ModuleScript", "UIKit", [=[
-- Small UI helpers so every screen shares one look.
local TweenService = game:GetService("TweenService")
local RunService = game:GetService("RunService")

local UIKit = {}

local viewportSetters = setmetatable({}, { __mode = "k" })

UIKit.Colors = {
	Bg = Color3.fromRGB(16, 18, 28),
	Panel = Color3.fromRGB(28, 31, 46),
	PanelLight = Color3.fromRGB(44, 48, 70),
	Text = Color3.fromRGB(245, 245, 250),
	SubText = Color3.fromRGB(170, 175, 195),
	Gold = Color3.fromRGB(255, 205, 70),
	Good = Color3.fromRGB(110, 230, 120),
	Bad = Color3.fromRGB(255, 90, 90),
	Day = Color3.fromRGB(255, 185, 60),
	Night = Color3.fromRGB(110, 90, 255),
	Berry = Color3.fromRGB(255, 110, 150),
	Accent = Color3.fromRGB(90, 200, 255),
}

UIKit.FamilyIcons = { Sprout = "🌿", Ember = "🔥", Shade = "🌑" }

function UIKit.new(className: string, props: { [string]: any }?, children: { Instance }?): any
	local inst = Instance.new(className)
	local parent = nil
	for key, value in props or {} do
		if key == "Parent" then
			parent = value
		else
			(inst :: any)[key] = value
		end
	end
	for _, child in children or {} do
		child.Parent = inst
	end
	if parent then
		inst.Parent = parent
	end
	return inst
end

function UIKit.corner(parent: Instance, radius: number?): UICorner
	return UIKit.new("UICorner", { CornerRadius = UDim.new(0, radius or 12), Parent = parent })
end

function UIKit.stroke(parent: Instance, color: Color3?, thickness: number?, transparency: number?): UIStroke
	return UIKit.new("UIStroke", {
		Color = color or Color3.new(0, 0, 0),
		Thickness = thickness or 2,
		Transparency = transparency or 0.4,
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		Parent = parent,
	})
end

function UIKit.padding(parent: Instance, px: number)
	return UIKit.new("UIPadding", {
		PaddingTop = UDim.new(0, px),
		PaddingBottom = UDim.new(0, px),
		PaddingLeft = UDim.new(0, px),
		PaddingRight = UDim.new(0, px),
		Parent = parent,
	})
end

function UIKit.panel(props: { [string]: any }): Frame
	local defaults = {
		BackgroundColor3 = UIKit.Colors.Panel,
		BackgroundTransparency = 0.1,
		BorderSizePixel = 0,
	}
	for k, v in props do
		defaults[k] = v
	end
	local frame = UIKit.new("Frame", defaults)
	UIKit.corner(frame, 12)
	UIKit.stroke(frame, Color3.new(0, 0, 0), 2, 0.5)
	return frame
end

function UIKit.text(props: { [string]: any }): TextLabel
	local defaults = {
		BackgroundTransparency = 1,
		Font = Enum.Font.GothamBold,
		TextColor3 = UIKit.Colors.Text,
		TextScaled = true,
		TextWrapped = true,
		TextStrokeTransparency = 0.6,
		Text = "",
	}
	for k, v in props do
		defaults[k] = v
	end
	return UIKit.new("TextLabel", defaults)
end

function UIKit.button(props: { [string]: any }, onClick: (() -> ())?): TextButton
	local defaults = {
		BackgroundColor3 = UIKit.Colors.PanelLight,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Font = Enum.Font.FredokaOne,
		TextColor3 = UIKit.Colors.Text,
		TextScaled = true,
		TextStrokeTransparency = 0.5,
		Text = "",
	}
	for k, v in props do
		defaults[k] = v
	end
	local button = UIKit.new("TextButton", defaults)
	UIKit.corner(button, 10)
	UIKit.stroke(button, Color3.new(0, 0, 0), 2, 0.4)
	UIKit.new("UITextSizeConstraint", { MaxTextSize = 44, Parent = button })
	UIKit.decorate(button)
	if onClick then
		button.Activated:Connect(onClick)
	end
	return button
end

-- Hover/press bounce for any button, including ones a designer made in Studio. Safe to call twice.
local decorated = setmetatable({}, { __mode = "k" })
function UIKit.decorate(button: GuiButton)
	if decorated[button] or not button:IsA("GuiButton") then
		return
	end
	decorated[button] = true
	local scale = button:FindFirstChildOfClass("UIScale") or UIKit.new("UIScale", { Parent = button })
	local base = scale.Scale
	button.MouseEnter:Connect(function()
		UIKit.tween(scale, 0.1, { Scale = base * 1.05 })
	end)
	button.MouseLeave:Connect(function()
		UIKit.tween(scale, 0.1, { Scale = base })
	end)
	button.MouseButton1Down:Connect(function()
		UIKit.tween(scale, 0.06, { Scale = base * 0.94 })
	end)
	button.MouseButton1Up:Connect(function()
		UIKit.tween(scale, 0.1, { Scale = base })
	end)
end

-- Multiplies a UDim2 (used to animate designer-sized frames relative to their own size).
function UIKit.scaleUDim2(size: UDim2, k: number): UDim2
	return UDim2.new(size.X.Scale * k, size.X.Offset * k, size.Y.Scale * k, size.Y.Offset * k)
end

function UIKit.bar(props: { [string]: any }, fillColor: Color3): (Frame, Frame)
	local back = UIKit.new("Frame", {
		BackgroundColor3 = Color3.fromRGB(12, 12, 18),
		BorderSizePixel = 0,
	})
	for k, v in props do
		(back :: any)[k] = v
	end
	UIKit.corner(back, 6)
	local fill = UIKit.new("Frame", {
		Name = "Fill",
		BackgroundColor3 = fillColor,
		BorderSizePixel = 0,
		Size = UDim2.fromScale(1, 1),
		Parent = back,
	})
	UIKit.corner(fill, 6)
	return back, fill
end

function UIKit.tween(inst: Instance, time: number, props: { [string]: any }, style: Enum.EasingStyle?, direction: Enum.EasingDirection?): Tween
	local tween = TweenService:Create(inst, TweenInfo.new(time, style or Enum.EasingStyle.Quad, direction or Enum.EasingDirection.Out), props)
	tween:Play()
	return tween
end

function UIKit.formatTime(seconds: number): string
	local s = math.max(0, math.floor(seconds))
	return ("%d:%02d"):format(s // 60, s % 60)
end

function UIKit.formatNumber(n: number): string
	if n >= 1e6 then
		return ("%.1fM"):format(n / 1e6)
	elseif n >= 1e4 then
		return ("%.1fK"):format(n / 1e3)
	end
	return tostring(math.floor(n))
end

-- Renders a model in a ViewportFrame, optionally spinning. Destroying the viewport stops the spin.
function UIKit.viewport(props: { [string]: any }, model: Model?, spin: boolean?): ViewportFrame
	local defaults = {
		BackgroundTransparency = 1,
		Ambient = Color3.fromRGB(160, 160, 170),
		LightColor = Color3.fromRGB(255, 255, 255),
		LightDirection = Vector3.new(-1, -1, -1),
	}
	for k, v in props do
		defaults[k] = v
	end
	local vp = UIKit.new("ViewportFrame", defaults)
	local camera = UIKit.new("Camera", { FieldOfView = 40, Parent = vp })
	vp.CurrentCamera = camera

	local current: Model? = nil
	local angle = 0
	local connection: RBXScriptConnection? = nil

	local function setModel(newModel: Model?)
		if current then
			current:Destroy()
		end
		current = newModel
		if not newModel then
			return
		end
		newModel:PivotTo(CFrame.new())
		newModel.Parent = vp
		local boxCFrame, size = newModel:GetBoundingBox()
		local center = Vector3.new(0, boxCFrame.Position.Y, 0)
		local radius = size.Magnitude / 2
		local distance = radius / math.tan(math.rad(camera.FieldOfView / 2)) * 1.05
		camera.CFrame = CFrame.lookAt(center + Vector3.new(0.45, 0.35, -1).Unit * distance, center)
	end
	setModel(model)

	if spin then
		connection = RunService.RenderStepped:Connect(function(dt)
			angle += dt * 0.9
			if current and current.Parent then
				current:PivotTo(CFrame.Angles(0, angle, 0))
			end
		end)
		vp.Destroying:Connect(function()
			if connection then
				connection:Disconnect()
			end
		end)
	end

	viewportSetters[vp] = setModel
	return vp
end

function UIKit.setViewportModel(vp: ViewportFrame, model: Model?)
	local setter = viewportSetters[vp]
	if setter then
		setter(model)
	end
end

return UIKit
]=])
print("✅ HATCH OR DIE Part 4/4 done. All done! Press Play to test, then File > Publish to Roblox.")
